package site.addzero.kcloud.plugins.codegencontext.codegen_context.service

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteIfExists
import kotlin.io.path.exists
import kotlin.io.path.isDirectory
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.name
import kotlin.io.path.readText
import org.koin.core.annotation.Single
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenContextDetailDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenFieldDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenSchemaDto
import site.addzero.kcloud.plugins.codegencontext.api.context.GenerateContractsResponseDto
import site.addzero.kcloud.plugins.codegencontext.codegen_context.routes.common.BusinessValidationException
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenConsumerTarget
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenFunctionCode
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenTransportType

private const val GENERATED_MARKER = "Generated by codegen-context. DO NOT EDIT."
private const val MCU_DEVICE_PACKAGE = "site.addzero.kcloud.plugins.mcuconsole.modbus.device"

@Single
class CodegenContextContractGenerator {

    fun generate(
        context: CodegenContextDetailDto,
    ): GenerateContractsResponseDto {
        if (context.consumerTarget != CodegenConsumerTarget.MCU_CONSOLE) {
            throw BusinessValidationException("Only MCU_CONSOLE is supported in V1.")
        }
        val contextId = context.id ?: throw BusinessValidationException("Context id is required for generation.")
        val roots = locateGeneratedRoots()
        val rendered = render(context, roots.workspaceRoot)
        writeRenderedFiles(rendered, roots)
        val generatedFiles =
            buildList {
                add(roots.serverPackageDir.resolve("DeviceApi.kt").toAbsolutePath().normalize().toString())
                add(roots.serverPackageDir.resolve("DeviceWriteApi.kt").toAbsolutePath().normalize().toString())
                rendered.registerDtos.keys.sorted().forEach { fileName ->
                    add(roots.sharedPackageDir.resolve(fileName).toAbsolutePath().normalize().toString())
                }
            }
        return GenerateContractsResponseDto(
            contextId = contextId,
            generatedFiles = generatedFiles,
            message = "Generated ${generatedFiles.size} contract files for ${context.code}.",
        )
    }

    internal fun render(
        context: CodegenContextDetailDto,
        workspaceRoot: Path,
    ): RenderedContracts {
        val sortedSchemas = context.schemas.sortedBy { it.sortIndex }
        val readSchemas = sortedSchemas.filter { it.direction.name == "READ" }
        val writeSchemas = sortedSchemas.filter { it.direction.name == "WRITE" }
        val registerDtos =
            readSchemas.associate { schema ->
                val modelName = schema.modelName.orEmpty()
                "${modelName}Registers.kt" to renderRegisterDto(schema, workspaceRoot)
            }
        return RenderedContracts(
            deviceApi = renderReadApi(readSchemas),
            deviceWriteApi = renderWriteApi(writeSchemas),
            registerDtos = registerDtos,
        )
    }

    private fun locateGeneratedRoots(): GeneratedRoots {
        val workspaceRoot = locateWorkspaceRoot()
        val serverRoot =
            workspaceRoot.resolve("apps/kcloud/plugins/mcu-console/server/generated/jvmMain/kotlin")
        val sharedRoot =
            workspaceRoot.resolve("apps/kcloud/plugins/mcu-console/shared/generated/commonMain/kotlin")
        val serverPackageDir = safeResolve(serverRoot, "site/addzero/kcloud/plugins/mcuconsole/modbus/device")
        val sharedPackageDir = safeResolve(sharedRoot, "site/addzero/kcloud/plugins/mcuconsole/modbus/device")
        return GeneratedRoots(
            workspaceRoot = workspaceRoot,
            serverPackageDir = serverPackageDir,
            sharedPackageDir = sharedPackageDir,
        )
    }

    private fun locateWorkspaceRoot(): Path {
        val overrideRoot = System.getProperty("codegen.context.repoRoot")?.takeIf(String::isNotBlank)
        var current =
            Path.of(overrideRoot ?: System.getProperty("user.dir"))
                .toAbsolutePath()
                .normalize()
        while (true) {
            if (current.resolve("settings.gradle.kts").exists() &&
                current.resolve("apps/kcloud/plugins/mcu-console").isDirectory()
            ) {
                return current
            }
            current = current.parent ?: break
        }
        throw BusinessValidationException("Unable to locate the kmp-aio workspace root.")
    }

    private fun safeResolve(
        root: Path,
        relative: String,
    ): Path {
        val normalizedRoot = root.toAbsolutePath().normalize()
        val target = normalizedRoot.resolve(relative).normalize()
        if (!target.startsWith(normalizedRoot)) {
            throw BusinessValidationException("Refuse to write outside generated roots: $target")
        }
        return target
    }

    private fun writeRenderedFiles(
        rendered: RenderedContracts,
        roots: GeneratedRoots,
    ) {
        roots.serverPackageDir.createDirectories()
        roots.sharedPackageDir.createDirectories()
        writeFile(roots.serverPackageDir.resolve("DeviceApi.kt"), rendered.deviceApi)
        writeFile(roots.serverPackageDir.resolve("DeviceWriteApi.kt"), rendered.deviceWriteApi)
        roots.sharedPackageDir.listDirectoryEntries("*.kt").forEach { existing ->
            if (existing.name.endsWith("Registers.kt")) {
                existing.deleteIfExists()
            }
        }
        rendered.registerDtos.forEach { (fileName, content) ->
            writeFile(roots.sharedPackageDir.resolve(fileName), content)
        }
    }

    private fun writeFile(
        target: Path,
        content: String,
    ) {
        target.parent?.createDirectories()
        Files.writeString(
            target,
            content,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING,
            StandardOpenOption.WRITE,
        )
    }

    private fun renderReadApi(
        schemas: List<CodegenSchemaDto>,
    ): String {
        val body =
            if (schemas.isEmpty()) {
                ""
            } else {
                schemas.joinToString("\n\n") { schema ->
                    """
    @ModbusOperation(
        address = ${schema.baseAddress},
        functionCode = ModbusFunctionCode.${schema.functionCode.name},
    )
    suspend fun ${schema.methodName}(): ${schema.modelName}Registers
                    """.trimEnd()
                }
            }

        return """
// $GENERATED_MARKER
package $MCU_DEVICE_PACKAGE

import site.addzero.device.protocol.modbus.annotation.ModbusOperation
import site.addzero.device.protocol.modbus.model.ModbusFunctionCode

interface DeviceApi {
${body.ifBlank { "" }}
}
        """.trimIndent() + "\n"
    }

    private fun renderWriteApi(
        schemas: List<CodegenSchemaDto>,
    ): String {
        val body =
            if (schemas.isEmpty()) {
                ""
            } else {
                schemas.joinToString("\n\n") { schema ->
                    val params =
                        schema.fields.sortedBy { it.sortIndex }.mapIndexed { index, field ->
                            buildString {
                                append("        @ModbusParam(order = ")
                                append(index)
                                append(", codec = ModbusCodec.")
                                append(field.transportType.name)
                                if (field.registerOffset != 0) {
                                    append(", registerOffset = ")
                                    append(field.registerOffset)
                                }
                                if (field.bitOffset != 0) {
                                    append(", bitOffset = ")
                                    append(field.bitOffset)
                                }
                                if (requiresLength(field)) {
                                    append(", length = ")
                                    append(field.length)
                                }
                                appendLine(")")
                                append("        ")
                                append(field.propertyName)
                                append(": ")
                                append(field.transportType.kotlinTypeName())
                            }
                        }.joinToString(",\n")

                    """
    @ModbusOperation(
        address = ${schema.baseAddress},
        functionCode = ModbusFunctionCode.${schema.functionCode.name},
    )
    suspend fun ${schema.methodName}(
$params
    ): ModbusCommandResult
                    """.trimEnd()
                }
            }

        return """
// $GENERATED_MARKER
package $MCU_DEVICE_PACKAGE

import site.addzero.device.protocol.modbus.annotation.ModbusOperation
import site.addzero.device.protocol.modbus.annotation.ModbusParam
import site.addzero.device.protocol.modbus.model.ModbusCodec
import site.addzero.device.protocol.modbus.model.ModbusCommandResult
import site.addzero.device.protocol.modbus.model.ModbusFunctionCode

interface DeviceWriteApi {
${body.ifBlank { "" }}
}
        """.trimIndent() + "\n"
    }

    private fun renderRegisterDto(
        schema: CodegenSchemaDto,
        workspaceRoot: Path,
    ): String {
        val modelName = schema.modelName ?: error("Validated READ schema requires modelName")
        val properties =
            schema.fields.sortedBy { it.sortIndex }.joinToString(",\n") { field ->
                val annotationArgs =
                    buildList {
                        add("codec = ModbusCodec.${field.transportType.name}")
                        add("registerOffset = ${field.registerOffset}")
                        if (field.bitOffset != 0) {
                            add("bitOffset = ${field.bitOffset}")
                        }
                        if (requiresLength(field)) {
                            add("length = ${field.length}")
                        }
                    }.joinToString(", ")
                buildString {
                    append("    @ModbusField(")
                    append(annotationArgs)
                    appendLine(")")
                    append("    val ")
                    append(field.propertyName)
                    append(": ")
                    append(field.transportType.kotlinTypeName())
                }
            }
        val apiModelPath =
            workspaceRoot.resolve(
                "apps/kcloud/plugins/mcu-console/shared/src/commonMain/kotlin/" +
                    "site/addzero/kcloud/plugins/mcuconsole/modbus/device/$modelName.kt",
            )
        val toApiModel =
            if (apiModelPath.exists()) {
                val propertyAssignments =
                    schema.fields.sortedBy { it.sortIndex }.joinToString(",\n") { field ->
                        "            ${field.propertyName} = ${field.propertyName}"
                    }
                """

    fun toApiModel(): $modelName {
        return $modelName(
$propertyAssignments,
        )
    }
                """.trimEnd()
            } else {
                ""
            }

        return """
// $GENERATED_MARKER
package $MCU_DEVICE_PACKAGE

import site.addzero.device.protocol.modbus.annotation.ModbusField
import site.addzero.device.protocol.modbus.model.ModbusCodec

data class ${modelName}Registers(
$properties,
) {$toApiModel
}
        """.trimIndent() + "\n"
    }

    private fun requiresLength(
        field: CodegenFieldDto,
    ): Boolean {
        return when (field.transportType) {
            CodegenTransportType.STRING_ASCII,
            CodegenTransportType.STRING_UTF8 -> true
            else -> false
        }
    }
}

internal data class RenderedContracts(
    val deviceApi: String,
    val deviceWriteApi: String,
    val registerDtos: Map<String, String>,
)

internal data class GeneratedRoots(
    val workspaceRoot: Path,
    val serverPackageDir: Path,
    val sharedPackageDir: Path,
)

private fun CodegenTransportType.kotlinTypeName(): String =
    when (this) {
        CodegenTransportType.BOOL_COIL -> "Boolean"
        CodegenTransportType.U16,
        CodegenTransportType.U32_BE -> "Int"
        CodegenTransportType.STRING_ASCII,
        CodegenTransportType.STRING_UTF8 -> "String"
    }
