package site.addzero.kcloud.plugins.codegencontext.codegen_context.service

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.sql.DriverManager
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteIfExists
import kotlin.io.path.exists
import kotlin.io.path.isRegularFile
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.name
import site.addzero.device.protocol.modbus.codegen.ModbusDtoCustomization
import site.addzero.device.protocol.modbus.codegen.ModbusKotlinContractGenerationRequest
import site.addzero.device.protocol.modbus.codegen.ModbusKotlinContractGenerator
import site.addzero.device.protocol.modbus.codegen.ModbusMetadataJsonCodec
import site.addzero.device.protocol.modbus.codegen.model.GeneratedArtifact as CodegenGeneratedArtifact
import site.addzero.device.protocol.modbus.codegen.model.ModbusDocModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusFieldModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusMqttTransportDefaults
import site.addzero.device.protocol.modbus.codegen.model.ModbusOperationModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusParameterModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusPropertyModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnTypeModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusRtuTransportDefaults
import site.addzero.device.protocol.modbus.codegen.model.ModbusServiceModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusTcpTransportDefaults
import site.addzero.device.protocol.modbus.codegen.model.ModbusTransportDefaults
import site.addzero.device.protocol.modbus.codegen.model.ModbusTransportKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusValueKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusWorkflowKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusWorkflowModel
import site.addzero.device.protocol.modbus.ksp.core.GeneratedArtifact as KspGeneratedArtifact
import site.addzero.device.protocol.modbus.ksp.core.ModbusArtifactRenderer
import site.addzero.device.protocol.modbus.ksp.core.ModbusDocModel as KspDocModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusFieldModel as KspFieldModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusMqttTransportDefaults as KspModbusMqttTransportDefaults
import site.addzero.device.protocol.modbus.ksp.core.ModbusOperationModel as KspOperationModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusParameterModel as KspParameterModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusPropertyModel as KspPropertyModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusReturnKind as KspReturnKind
import site.addzero.device.protocol.modbus.ksp.core.ModbusReturnTypeModel as KspReturnTypeModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusRtuTransportDefaults as KspModbusRtuTransportDefaults
import site.addzero.device.protocol.modbus.ksp.core.ModbusServerRouteMode
import site.addzero.device.protocol.modbus.ksp.core.ModbusServiceModel as KspServiceModel
import site.addzero.device.protocol.modbus.ksp.core.ModbusTcpTransportDefaults as KspModbusTcpTransportDefaults
import site.addzero.device.protocol.modbus.ksp.core.ModbusTransportDefaults as KspTransportDefaults
import site.addzero.device.protocol.modbus.ksp.core.ModbusTransportKind as KspTransportKind
import site.addzero.device.protocol.modbus.ksp.core.ModbusValueKind as KspValueKind
import site.addzero.device.protocol.modbus.ksp.core.ModbusWorkflowKind as KspWorkflowKind
import site.addzero.device.protocol.modbus.ksp.core.ModbusWorkflowModel as KspWorkflowModel

private const val BUILD_GENERATED_MARKER = "Generated by codegen-context. DO NOT EDIT."
private const val BUILD_DEVICE_PACKAGE = "site.addzero.kcloud.plugins.mcuconsole.modbus.device"
private val BUILD_SUPPORTED_INTERFACES = setOf("DeviceApi", "DeviceWriteApi")

/**
 * 处理main。
 *
 * @param args SQL 参数列表。
 */
fun main(args: Array<String>) {
    val options = BuildCliOptions.parse(args)
    val requestedTransports = options.transports().toList()
    val payloadsByTransport = linkedMapOf<ModbusTransportKind, List<String>>()

    requestedTransports.forEach { transport ->
        val payloads = options.loadPayloads(transport)
        if (payloads.isNotEmpty()) {
            payloadsByTransport[transport] = payloads
        }
    }

    check(payloadsByTransport.isNotEmpty()) {
        "No metadata payloads were loaded for transports=${options.transport}."
    }

    val fallbackTransport = payloadsByTransport.keys.first()
    val fallbackPayloads = requireNotNull(payloadsByTransport[fallbackTransport])
    val fallbackServices = options.decodeServices(fallbackPayloads, fallbackTransport)
    val servicesByTransport = linkedMapOf<ModbusTransportKind, List<ModbusServiceModel>>()

    requestedTransports.forEach { transport ->
        val services =
            payloadsByTransport[transport]?.let { payloads ->
                options.decodeServices(payloads, transport)
            } ?: run {
                check(options.skipMissingTransports) {
                    "No metadata services matched ${options.contractPackage} for transport ${transport.transportId}."
                }
                println(
                    "codegen-context: transport ${transport.transportId} 缺少独立 metadata，改用 ${fallbackTransport.transportId} 快照派生生成产物。",
                )
                fallbackServices.deriveForTransport(
                    sourceTransport = fallbackTransport,
                    targetTransport = transport,
                )
            }
        if (services.isEmpty()) {
            check(options.skipMissingTransports) {
                "No metadata services matched ${options.contractPackage} for transport ${transport.transportId}."
            }
            return@forEach
        }
        servicesByTransport[transport] = services
    }

    check(servicesByTransport.isNotEmpty()) {
        "No metadata services were loaded for transports=${options.transport}."
    }

    val contractServices = servicesByTransport.values.first()
    val resolvedTransportDefaults = options.transportDefaults.toKspTransportDefaults()

    if (options.serverOutputRoot != null || options.sharedOutputRoot != null) {
        require(options.serverOutputRoot != null && options.sharedOutputRoot != null) {
            "Both --server-output-root and --shared-output-root are required when generating Kotlin contracts."
        }
        val dtoCustomizations = buildDtoCustomizations(contractServices)
        val artifacts =
            ModbusKotlinContractGenerator.render(
                ModbusKotlinContractGenerationRequest(
                    services = contractServices,
                    fileHeader = BUILD_GENERATED_MARKER,
                    dtoCustomizations = dtoCustomizations,
                ),
            )
        writeContractArtifacts(
            artifacts = artifacts,
            serverOutputRoot = requireNotNull(options.serverOutputRoot),
            sharedOutputRoot = requireNotNull(options.sharedOutputRoot),
            contractPackage = options.contractPackage,
            supportedInterfaces = options.supportedInterfaces,
        )
    }

    servicesByTransport.forEach { (transport, services) ->
        val kspTransport = transport.toKspTransportKind()
        val kspServices = services.map(ModbusServiceModel::toKspServiceModel)
        val gatewayOutputRoot = options.gatewayOutputRoot ?: options.serverOutputRoot
        if (gatewayOutputRoot != null) {
            cleanupPackageDir(gatewayOutputRoot, kspTransport.generatedPackage.replace('.', '/'))
            val serverRouteMode =
                if (options.springRouteOutputRoot == null) {
                    ModbusServerRouteMode.DIRECT_KTOR
                } else {
                    ModbusServerRouteMode.SPRING_SOURCE
                }
            writeKspArtifacts(
                outputRoot = gatewayOutputRoot,
                artifacts =
                    ModbusArtifactRenderer.renderServerArtifacts(
                        transport = kspTransport,
                        services = kspServices,
                        transportDefaults = resolvedTransportDefaults,
                        serverRouteMode = serverRouteMode,
                    ),
            )
        }
        if (options.springRouteOutputRoot != null) {
            cleanupPackageDir(options.springRouteOutputRoot, kspTransport.generatedPackage.replace('.', '/'))
            writeKspArtifacts(
                outputRoot = options.springRouteOutputRoot,
                artifacts = ModbusArtifactRenderer.renderSpringRouteSourceArtifacts(kspTransport, kspServices),
            )
        }
        if (options.cOutputRoot != null) {
            cleanupPackageDir(options.cOutputRoot, "generated/modbus/${transport.transportId}")
            val cArtifacts =
                buildList {
                    kspServices.forEach { service ->
                        addAll(ModbusArtifactRenderer.renderServiceContractArtifacts(service, resolvedTransportDefaults))
                        addAll(
                            ModbusArtifactRenderer
                                .renderMarkdownArtifacts(service, resolvedTransportDefaults)
                                .filter { artifact -> artifact.extensionName == "c" },
                        )
                    }
                    addAll(ModbusArtifactRenderer.renderTransportContractArtifacts(kspTransport, kspServices, resolvedTransportDefaults))
                }
            writeKspArtifacts(options.cOutputRoot, cArtifacts)
        }
        if (options.markdownOutputRoot != null) {
            cleanupMarkdownArtifacts(options.markdownOutputRoot, transport)
            val markdownArtifacts =
                kspServices.flatMap { service ->
                    ModbusArtifactRenderer
                        .renderMarkdownArtifacts(service, resolvedTransportDefaults)
                        .filter { artifact -> artifact.extensionName == "md" }
                }
            writeKspArtifacts(options.markdownOutputRoot, markdownArtifacts)
        }
    }
}

/**
 * 表示构建命令行选项。
 *
 * @property driverClass driver类。
 * @property jdbcUrl JDBC地址。
 * @property username 用户名。
 * @property password 密码。
 * @property query 查询。
 * @property jsonColumn jsoncolumn。
 * @property transport 传输。
 * @property workspaceRoot workspace根目录。
 * @property serverOutputRoot 服务端输出根目录。
 * @property sharedOutputRoot 共享输出根目录。
 * @property gatewayOutputRoot 网关输出根目录。
 * @property cOutputRoot C 输出根目录。
 * @property markdownOutputRoot Markdown 输出根目录。
 * @property springRouteOutputRoot Spring 路由输出根目录。
 * @property contractPackage contract包。
 * @property supportedInterfaces supportedinterfaces。
 * @property skipMissingTransports skipmissing传输。
 * @property transportDefaults 传输默认。
 */
private data class BuildCliOptions(
    val driverClass: String,
    val jdbcUrl: String,
    val username: String?,
    val password: String?,
    val query: String,
    val jsonColumn: String?,
    val transport: String,
    val workspaceRoot: Path?,
    val serverOutputRoot: Path?,
    val sharedOutputRoot: Path?,
    val gatewayOutputRoot: Path?,
    val cOutputRoot: Path?,
    val markdownOutputRoot: Path?,
    val springRouteOutputRoot: Path?,
    val contractPackage: String,
    val supportedInterfaces: Set<String>,
    val skipMissingTransports: Boolean,
    val transportDefaults: ModbusTransportDefaults,
) {
    /**
     * 处理传输。
     */
    fun transports(): Set<ModbusTransportKind> {
        val transports = ModbusTransportKind.parseConfigured(transport)
        require(transports.isNotEmpty()) {
            "At least one transport must be specified via --transport."
        }
        return transports
    }

    /**
     * 加载payloads。
     *
     * @param transport 传输。
     */
    fun loadPayloads(
        transport: ModbusTransportKind,
    ): List<String> {
        Class.forName(driverClass)
        val payloads = mutableListOf<String>()
        openConnection().use { connection ->
            val resolvedQuery =
                query
                    .replace("\${transport}", transport.transportId)
                    .replace("\${transportName}", transport.name)
            connection.prepareStatement(resolvedQuery).use { statement ->
                statement.executeQuery().use { resultSet ->
                    while (resultSet.next()) {
                        val payload =
                            if (jsonColumn.isNullOrBlank()) {
                                resultSet.getString(1)
                            } else {
                                resultSet.getString(jsonColumn)
                            }
                        payload
                            ?.trim()
                            ?.takeIf(String::isNotBlank)
                            ?.let(payloads::add)
                    }
                }
            }
        }
        return payloads
    }

    private fun openConnection() =
        if (username == null && password == null) {
            DriverManager.getConnection(jdbcUrl)
        } else {
            DriverManager.getConnection(jdbcUrl, username, password)
        }

    /**
     * 处理decode服务。
     *
     * @param payloads 载荷。
     * @param transport 传输。
     */
    fun decodeServices(
        payloads: List<String>,
        transport: ModbusTransportKind,
    ): List<ModbusServiceModel> =
        payloads
            .flatMap { payload ->
                ModbusMetadataJsonCodec.decodeServices(
                    payload = payload,
                    transport = transport,
                    contractPackages = listOf(contractPackage),
                )
            }.filter { service ->
                service.interfacePackage == contractPackage &&
                    service.interfaceSimpleName in supportedInterfaces
            }.distinctBy(ModbusServiceModel::interfaceQualifiedName)

    companion object {
        /**
         * 处理parse。
         *
         * @param args SQL 参数列表。
         */
        fun parse(
            args: Array<String>,
        ): BuildCliOptions {
            val pairs = mutableMapOf<String, String>()
            var index = 0
            while (index < args.size) {
                val key = args[index]
                require(key.startsWith("--")) {
                    "Unsupported argument $key. Use --key value pairs."
                }
                require(index + 1 < args.size) {
                    "Missing value for argument $key."
                }
                pairs[key.removePrefix("--")] = args[index + 1]
                index += 2
            }
            val workspaceRoot = pairs["workspace-root"]?.let { Path.of(it).toAbsolutePath().normalize() }
            return BuildCliOptions(
                driverClass = pairs.getValue("driver-class"),
                jdbcUrl = pairs.getValue("jdbc-url"),
                username = pairs["username"],
                password = pairs["password"],
                query = pairs.getValue("query"),
                jsonColumn = pairs["json-column"],
                transport = pairs.getValue("transport"),
                workspaceRoot = workspaceRoot,
                serverOutputRoot = resolveOptionalRoot(workspaceRoot, pairs["server-output-root"]),
                sharedOutputRoot = resolveOptionalRoot(workspaceRoot, pairs["shared-output-root"]),
                gatewayOutputRoot = resolveOptionalRoot(workspaceRoot, pairs["gateway-output-root"]),
                cOutputRoot = resolveOptionalRoot(workspaceRoot, pairs["c-output-root"]),
                markdownOutputRoot = resolveOptionalRoot(workspaceRoot, pairs["markdown-output-root"]),
                springRouteOutputRoot = resolveOptionalRoot(workspaceRoot, pairs["spring-route-output-root"]),
                contractPackage = pairs["contract-package"]?.ifBlank { BUILD_DEVICE_PACKAGE } ?: BUILD_DEVICE_PACKAGE,
                supportedInterfaces =
                    pairs["supported-interfaces"]
                        ?.split(',', ';', '\n')
                        ?.map(String::trim)
                        ?.filter(String::isNotBlank)
                        ?.toSet()
                        .orEmpty()
                        .ifEmpty { BUILD_SUPPORTED_INTERFACES },
                skipMissingTransports = pairs["skip-missing-transports"].toBooleanFlag(defaultValue = false),
                transportDefaults =
                    ModbusTransportDefaults(
                        rtu =
                            ModbusRtuTransportDefaults(
                                portPath = pairs["rtu-port-path"].orEmpty().ifBlank { "/dev/ttyUSB0" },
                                unitId = pairs["rtu-unit-id"].toIntOrDefault(1),
                                baudRate = pairs["rtu-baud-rate"].toIntOrDefault(9600),
                                dataBits = pairs["rtu-data-bits"].toIntOrDefault(8),
                                stopBits = pairs["rtu-stop-bits"].toIntOrDefault(1),
                                parity = pairs["rtu-parity"].orEmpty().ifBlank { "none" },
                                timeoutMs = pairs["rtu-timeout-ms"].toLongOrDefault(1_000),
                                retries = pairs["rtu-retries"].toIntOrDefault(2),
                            ),
                        tcp =
                            ModbusTcpTransportDefaults(
                                host = pairs["tcp-host"].orEmpty().ifBlank { "127.0.0.1" },
                                port = pairs["tcp-port"].toIntOrDefault(502),
                                unitId = pairs["tcp-unit-id"].toIntOrDefault(1),
                                timeoutMs = pairs["tcp-timeout-ms"].toLongOrDefault(1_000),
                                retries = pairs["tcp-retries"].toIntOrDefault(2),
                            ),
                        mqtt =
                            ModbusMqttTransportDefaults(
                                brokerUrl = pairs["mqtt-broker-url"].orEmpty().ifBlank { "tcp://127.0.0.1:1883" },
                                clientId = pairs["mqtt-client-id"].orEmpty().ifBlank { "modbus-mqtt-client" },
                                requestTopic = pairs["mqtt-request-topic"].orEmpty().ifBlank { "modbus/request" },
                                responseTopic = pairs["mqtt-response-topic"].orEmpty().ifBlank { "modbus/response" },
                                qos = pairs["mqtt-qos"].toIntOrDefault(1),
                                timeoutMs = pairs["mqtt-timeout-ms"].toLongOrDefault(1_000),
                                retries = pairs["mqtt-retries"].toIntOrDefault(2),
                            ),
                    ),
            )
        }

        /**
         * 解析optional根目录。
         *
         * @param workspaceRoot workspace根目录。
         * @param rawValue 原始值。
         */
        private fun resolveOptionalRoot(
            workspaceRoot: Path?,
            rawValue: String?,
        ): Path? {
            val value = rawValue?.trim()?.takeIf(String::isNotBlank) ?: return null
            val path = Path.of(value)
            return if (path.isAbsolute) {
                path.normalize()
            } else {
                requireNotNull(workspaceRoot) {
                    "Relative output roots require --workspace-root."
                }.resolve(path).normalize()
            }
        }
    }
}

/**
 * 构建数据传输对象customizations。
 *
 * @param services 服务。
 */
private fun buildDtoCustomizations(
    services: List<ModbusServiceModel>,
): Map<String, ModbusDtoCustomization> =
    services
        .asSequence()
        .filter { service -> service.interfaceSimpleName == "DeviceApi" }
        .flatMap { service -> service.operations.asSequence() }
        .filter { operation ->
            operation.returnType.kind == ModbusReturnKind.DTO &&
                operation.returnType.simpleName.endsWith("Registers")
        }.associate { operation ->
            val dtoType = operation.returnType
            val propertyDocs =
                dtoType.properties.associate { property ->
                    property.name to
                        (
                            property.doc.cleanDocSummary()
                                ?: property.name
                            )
                }

            dtoType.qualifiedName to
                ModbusDtoCustomization(
                    summary =
                        dtoType.docSummary.cleanDocSummary() ?: dtoType.simpleName,
                    propertyDocs = propertyDocs,
                )
        }

/**
 * 处理列表。
 *
 * @param sourceTransport 来源传输。
 * @param targetTransport 目标传输。
 */
private fun List<ModbusServiceModel>.deriveForTransport(
    sourceTransport: ModbusTransportKind,
    targetTransport: ModbusTransportKind,
): List<ModbusServiceModel> =
    map { service ->
        service.deriveForTransport(sourceTransport = sourceTransport, targetTransport = targetTransport)
    }

/**
 * 处理modbus服务模型。
 *
 * @param sourceTransport 来源传输。
 * @param targetTransport 目标传输。
 */
private fun ModbusServiceModel.deriveForTransport(
    sourceTransport: ModbusTransportKind,
    targetTransport: ModbusTransportKind,
): ModbusServiceModel {
    if (sourceTransport == targetTransport) {
        return this
    }
    return copy(
        transport = targetTransport,
        operations =
            operations.map { operation ->
                operation.copy(
                    requestClassName = operation.requestClassName.rewriteTransportToken(sourceTransport, targetTransport),
                    requestQualifiedName = operation.requestQualifiedName.rewriteTransportToken(sourceTransport, targetTransport),
                )
            },
        workflows =
            workflows.map { workflow ->
                workflow.copy(
                    requestClassName = workflow.requestClassName.rewriteTransportToken(sourceTransport, targetTransport),
                    requestQualifiedName = workflow.requestQualifiedName.rewriteTransportToken(sourceTransport, targetTransport),
                )
            },
    )
}

/**
 * 处理string。
 *
 * @param sourceTransport 来源传输。
 * @param targetTransport 目标传输。
 */
private fun String.rewriteTransportToken(
    sourceTransport: ModbusTransportKind,
    targetTransport: ModbusTransportKind,
): String {
    if (sourceTransport == targetTransport) {
        return this
    }
    val sourceToken = sourceTransport.transportId.replaceFirstChar(Char::uppercase)
    val targetToken = targetTransport.transportId.replaceFirstChar(Char::uppercase)
    return replace(sourceToken, targetToken)
}

/**
 * 写入contract产物。
 *
 * @param artifacts artifacts。
 * @param serverOutputRoot 服务端输出根目录。
 * @param sharedOutputRoot 共享输出根目录。
 * @param contractPackage contract包。
 * @param supportedInterfaces supportedinterfaces。
 */
private fun writeContractArtifacts(
    artifacts: List<CodegenGeneratedArtifact>,
    serverOutputRoot: Path,
    sharedOutputRoot: Path,
    contractPackage: String,
    supportedInterfaces: Set<String>,
) {
    val packageRelativePath = contractPackage.replace('.', '/')
    val serverPackageDir = safeResolve(serverOutputRoot, packageRelativePath)
    val sharedPackageDir = safeResolve(sharedOutputRoot, packageRelativePath)
    val artifactsByFile = artifacts.associateBy(CodegenGeneratedArtifact::fileName)

    serverPackageDir.createDirectories()
    sharedPackageDir.createDirectories()

    supportedInterfaces.forEach { interfaceName ->
        val targetFile = serverPackageDir.resolve("$interfaceName.kt")
        val artifact = artifactsByFile[interfaceName]
        if (artifact == null) {
            targetFile.deleteIfExists()
        } else {
            writeFile(targetFile, artifact.content.normalizeGeneratedKotlin())
        }
    }

    sharedPackageDir.listDirectoryEntries("*.kt").forEach { existing ->
        if (existing.name.endsWith("Registers.kt")) {
            existing.deleteIfExists()
        }
    }
    artifacts
        .filter { artifact ->
            artifact.fileName.endsWith("Registers") &&
                artifact.packageName == contractPackage
        }.forEach { artifact ->
            writeFile(
                sharedPackageDir.resolve("${artifact.fileName}.kt"),
                artifact.content.normalizeGeneratedKotlin(),
            )
        }
}

/**
 * 写入ksp产物。
 *
 * @param outputRoot 输出根目录。
 * @param artifacts artifacts。
 */
private fun writeKspArtifacts(
    outputRoot: Path,
    artifacts: List<KspGeneratedArtifact>,
) {
    artifacts.forEach { artifact ->
        val relativePath =
            buildString {
                artifact.packageName
                    ?.takeIf(String::isNotBlank)
                    ?.let { packageName ->
                        append(packageName.replace('.', '/'))
                        append('/')
                    }
                append(artifact.fileName)
                append('.')
                append(artifact.extensionName)
            }
        val targetFile = safeResolve(outputRoot, relativePath)
        val content =
            if (artifact.extensionName == "kt") {
                artifact.content.normalizeGeneratedKotlin()
            } else {
                artifact.content
            }
        writeFile(targetFile, content)
    }
}

/**
 * 处理cleanup包dir。
 *
 * @param outputRoot 输出根目录。
 * @param relativePackagePath relative包路径。
 */
private fun cleanupPackageDir(
    outputRoot: Path,
    relativePackagePath: String,
) {
    val packageDir = safeResolve(outputRoot, relativePackagePath)
    if (packageDir.exists()) {
        packageDir.toFile().deleteRecursively()
    }
}

/**
 * 处理cleanupMarkdown产物。
 *
 * @param outputRoot 输出根目录。
 * @param transport 传输。
 */
private fun cleanupMarkdownArtifacts(
    outputRoot: Path,
    transport: ModbusTransportKind,
) {
    val markdownDir = safeResolve(outputRoot, "generated/modbus/protocols")
    if (!markdownDir.exists()) {
        return
    }
    markdownDir
        .listDirectoryEntries("*.md")
        .filter { file ->
            file.isRegularFile() && file.name.endsWith(".${transport.transportId}.protocol.md")
        }.forEach { file ->
            file.deleteIfExists()
        }
}

/**
 * 处理safe解析。
 *
 * @param root 根目录。
 * @param relative relative。
 */
private fun safeResolve(
    root: Path,
    relative: String,
): Path {
    val normalizedRoot = root.toAbsolutePath().normalize()
    val target = normalizedRoot.resolve(relative).normalize()
    check(target.startsWith(normalizedRoot)) {
        "Refuse to write outside generated roots: $target"
    }
    return target
}

/**
 * 写入file。
 *
 * @param target 目标。
 * @param content content。
 */
private fun writeFile(
    target: Path,
    content: String,
) {
    target.parent?.createDirectories()
    Files.writeString(
        target,
        content,
        StandardOpenOption.CREATE,
        StandardOpenOption.TRUNCATE_EXISTING,
        StandardOpenOption.WRITE,
    )
}

/**
 * 处理modbus传输默认。
 */
private fun ModbusTransportDefaults.toKspTransportDefaults(): KspTransportDefaults =
    KspTransportDefaults(
        rtu =
            KspModbusRtuTransportDefaults(
                portPath = rtu.portPath,
                unitId = rtu.unitId,
                baudRate = rtu.baudRate,
                dataBits = rtu.dataBits,
                stopBits = rtu.stopBits,
                parity = rtu.parity,
                timeoutMs = rtu.timeoutMs,
                retries = rtu.retries,
            ),
        tcp =
            KspModbusTcpTransportDefaults(
                host = tcp.host,
                port = tcp.port,
                unitId = tcp.unitId,
                timeoutMs = tcp.timeoutMs,
                retries = tcp.retries,
            ),
        mqtt =
            KspModbusMqttTransportDefaults(
                brokerUrl = mqtt.brokerUrl,
                clientId = mqtt.clientId,
                requestTopic = mqtt.requestTopic,
                responseTopic = mqtt.responseTopic,
                qos = mqtt.qos,
                timeoutMs = mqtt.timeoutMs,
                retries = mqtt.retries,
            ),
    )

/**
 * 处理modbus传输类型。
 */
private fun ModbusTransportKind.toKspTransportKind(): KspTransportKind =
    when (this) {
        ModbusTransportKind.RTU -> KspTransportKind.RTU
        ModbusTransportKind.TCP -> KspTransportKind.TCP
        ModbusTransportKind.MQTT -> KspTransportKind.MQTT
    }

/**
 * 处理modbus服务模型。
 */
private fun ModbusServiceModel.toKspServiceModel(): KspServiceModel =
    KspServiceModel(
        interfacePackage = interfacePackage,
        interfaceSimpleName = interfaceSimpleName,
        interfaceQualifiedName = interfaceQualifiedName,
        serviceId = serviceId,
        summary = summary,
        basePath = basePath,
        transport = transport.toKspTransportKind(),
        doc = doc.toKspDocModel(),
        operations = operations.map(ModbusOperationModel::toKspOperationModel),
        workflows = workflows.map(ModbusWorkflowModel::toKspWorkflowModel),
    )

/**
 * 处理modbusworkflow模型。
 */
private fun ModbusWorkflowModel.toKspWorkflowModel(): KspWorkflowModel =
    KspWorkflowModel(
        kind = kind.toKspWorkflowKind(),
        methodName = methodName,
        workflowId = workflowId,
        requestClassName = requestClassName,
        requestQualifiedName = requestQualifiedName,
        bytesParameterName = bytesParameterName,
        returnType = returnType.toKspReturnTypeModel(),
        doc = doc.toKspDocModel(),
        startMethodName = startMethodName,
        chunkMethodName = chunkMethodName,
        commitMethodName = commitMethodName,
        resetMethodName = resetMethodName,
    )

/**
 * 处理modbusworkflow类型。
 */
private fun ModbusWorkflowKind.toKspWorkflowKind(): KspWorkflowKind =
    when (this) {
        ModbusWorkflowKind.FLASH_FIRMWARE -> KspWorkflowKind.FLASH_FIRMWARE
    }

/**
 * 处理modbusoperation模型。
 */
private fun ModbusOperationModel.toKspOperationModel(): KspOperationModel =
    KspOperationModel(
        methodName = methodName,
        operationId = operationId,
        functionCodeName = functionCodeName,
        address = address,
        quantity = quantity,
        requestClassName = requestClassName,
        requestQualifiedName = requestQualifiedName,
        parameters = parameters.map(ModbusParameterModel::toKspParameterModel),
        returnType = returnType.toKspReturnTypeModel(),
        doc = doc.toKspDocModel(),
    )

/**
 * 处理modbusparameter模型。
 */
private fun ModbusParameterModel.toKspParameterModel(): KspParameterModel =
    KspParameterModel(
        name = name,
        qualifiedType = qualifiedType,
        valueKind = valueKind.toKspValueKind(),
        order = order,
        codecName = codecName,
        registerOffset = registerOffset,
        bitOffset = bitOffset,
        registerWidth = registerWidth,
        length = length,
        doc = doc,
    )

/**
 * 处理modbusreturn类型模型。
 */
private fun ModbusReturnTypeModel.toKspReturnTypeModel(): KspReturnTypeModel =
    KspReturnTypeModel(
        qualifiedName = qualifiedName,
        simpleName = simpleName,
        kind = kind.toKspReturnKind(),
        docSummary = docSummary,
        valueKind = valueKind?.toKspValueKind(),
        codecName = codecName,
        length = length,
        registerWidth = registerWidth,
        properties = properties.map(ModbusPropertyModel::toKspPropertyModel),
    )

/**
 * 处理modbusreturn类型。
 */
private fun ModbusReturnKind.toKspReturnKind(): KspReturnKind =
    when (this) {
        ModbusReturnKind.UNIT -> KspReturnKind.UNIT
        ModbusReturnKind.BOOLEAN -> KspReturnKind.BOOLEAN
        ModbusReturnKind.INT -> KspReturnKind.INT
        ModbusReturnKind.STRING -> KspReturnKind.STRING
        ModbusReturnKind.DTO -> KspReturnKind.DTO
        ModbusReturnKind.COMMAND_RESULT -> KspReturnKind.COMMAND_RESULT
    }

/**
 * 处理modbus属性模型。
 */
private fun ModbusPropertyModel.toKspPropertyModel(): KspPropertyModel =
    KspPropertyModel(
        name = name,
        qualifiedType = qualifiedType,
        valueKind = valueKind.toKspValueKind(),
        field = field?.toKspFieldModel(),
        doc = doc,
    )

/**
 * 处理modbus字段模型。
 */
private fun ModbusFieldModel.toKspFieldModel(): KspFieldModel =
    KspFieldModel(
        codecName = codecName,
        registerOffset = registerOffset,
        bitOffset = bitOffset,
        length = length,
        registerWidth = registerWidth,
    )

/**
 * 处理modbus值类型。
 */
private fun ModbusValueKind.toKspValueKind(): KspValueKind =
    when (this) {
        ModbusValueKind.BOOLEAN -> KspValueKind.BOOLEAN
        ModbusValueKind.INT -> KspValueKind.INT
        ModbusValueKind.BYTES -> KspValueKind.BYTES
        ModbusValueKind.STRING -> KspValueKind.STRING
    }

/**
 * 处理modbusdoc模型。
 */
private fun ModbusDocModel.toKspDocModel(): KspDocModel =
    KspDocModel(
        summary = summary,
        descriptionLines = descriptionLines,
        parameterDocs = parameterDocs,
    )

/**
 * 处理string。
 *
 * @param defaultValue 默认值。
 */
private fun String?.toBooleanFlag(defaultValue: Boolean): Boolean =
    when (this?.trim()?.lowercase()) {
        null -> defaultValue
        "1",
        "true",
        "yes",
        "y",
        "on",
        -> true
        "0",
        "false",
        "no",
        "n",
        "off",
        -> false
        else -> error("Unsupported boolean flag value: $this")
    }

/**
 * 处理string。
 *
 * @param defaultValue 默认值。
 */
private fun String?.toIntOrDefault(defaultValue: Int): Int =
    this
        ?.trim()
        ?.takeIf(String::isNotEmpty)
        ?.toIntOrNull()
        ?: defaultValue

/**
 * 处理string。
 *
 * @param defaultValue 默认值。
 */
private fun String?.toLongOrDefault(defaultValue: Long): Long =
    this
        ?.trim()
        ?.takeIf(String::isNotEmpty)
        ?.toLongOrNull()
        ?: defaultValue
