package site.addzero.kcloud.plugins.codegencontext.codegen_context.service

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.sql.Connection
import java.sql.PreparedStatement
import java.time.Instant
import javax.sql.DataSource
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteIfExists
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.name
import org.koin.core.annotation.Single
import site.addzero.device.protocol.modbus.codegen.ModbusContractDefaultsResolver
import site.addzero.device.protocol.modbus.codegen.ModbusDtoCustomization
import site.addzero.device.protocol.modbus.codegen.ModbusKotlinContractGenerationRequest
import site.addzero.device.protocol.modbus.codegen.ModbusKotlinContractGenerator
import site.addzero.device.protocol.modbus.codegen.ModbusMetadataJsonCodec
import site.addzero.device.protocol.modbus.codegen.model.GeneratedArtifact
import site.addzero.device.protocol.modbus.codegen.model.ModbusDocModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusFieldModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusOperationModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusParameterModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusPropertyModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnTypeModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusServiceModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusTransportKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusValueKind
import site.addzero.device.protocol.modbus.ksp.core.GeneratedArtifact as KspGeneratedArtifact
import site.addzero.device.protocol.modbus.ksp.core.ModbusArtifactRenderer
import site.addzero.device.protocol.modbus.ksp.core.ModbusExternalCArtifactWriter
import site.addzero.device.protocol.modbus.ksp.core.ModbusServerRouteMode
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenContextDetailDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenGeneratedArtifactDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenMetadataExportResultDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenMetadataExportSettingsDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenMetadataIssueDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenMetadataSnapshotResultDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenProjectSyncResultDto
import site.addzero.kcloud.plugins.codegencontext.api.context.GenerateContractsResponseDto
import site.addzero.kmp.exp.BusinessValidationException
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenConsumerTarget
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenMetadataArtifactKind
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenMetadataIssueSeverity
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenMetadataTransportKind
import site.addzero.device.protocol.modbus.ksp.core.ModbusTransportKind as KspTransportKind

private const val GENERATED_MARKER = "Generated by codegen-context. DO NOT EDIT."
private const val MCU_DEVICE_PACKAGE = "site.addzero.kcloud.plugins.mcuconsole.modbus.device"
private const val METADATA_TABLE = "codegen_context_modbus_contract"
private val EXTERNAL_ARTIFACT_TRANSPORTS = listOf(ModbusTransportKind.RTU, ModbusTransportKind.TCP, ModbusTransportKind.MQTT)

@Single
/**
 * 表示代码生成上下文contractgenerator。
 *
 * @property dataSource 数据来源。
 */
class CodegenContextContractGenerator(
    private val dataSource: DataSource,
) {
    fun export(
        context: CodegenContextDetailDto,
        exportSettings: CodegenMetadataExportSettingsDto,
    ): CodegenMetadataExportResultDto {
        if (context.consumerTarget != CodegenConsumerTarget.MCU_CONSOLE) {
            throw BusinessValidationException("Only MCU_CONSOLE is supported in V1.")
        }
        val contextId = context.id ?: throw BusinessValidationException("Context id is required for export.")
        val sourceTransport = context.modbusTransport()
        val sourceServices = context.toModbusServices()
        val metadataSnapshots = mutableListOf<CodegenMetadataSnapshotResultDto>()
        val generatedArtifacts = mutableListOf<CodegenGeneratedArtifactDto>()
        val projectSyncResults = mutableListOf<CodegenProjectSyncResultDto>()
        val issues = mutableListOf<CodegenMetadataIssueDto>()

        if (CodegenMetadataArtifactKind.METADATA_SNAPSHOT in exportSettings.artifactKinds) {
            syncMetadataSnapshotSelections(contextId, exportSettings.kotlinClientTransports)
            exportSettings.kotlinClientTransports
                .sortedBy(CodegenMetadataTransportKind::name)
                .forEach { transport ->
                    val services =
                        sourceServices.deriveForTransport(
                            sourceTransport = sourceTransport,
                            targetTransport = transport.toCodegenTransportKind(),
                        )
                    val payload = ModbusMetadataJsonCodec.encodeServices(services)
                    upsertMetadataSnapshot(
                        context = context,
                        transport = transport.toCodegenTransportKind(),
                        payload = payload,
                    )
                    metadataSnapshots +=
                        CodegenMetadataSnapshotResultDto(
                            transport = transport,
                            tableName = METADATA_TABLE,
                            contextCode = context.code,
                            selected = true,
                            queryHint = buildMetadataSnapshotQueryHint(transport),
                        )
                }
        }

        if (exportSettings.artifactKinds.any { artifactKind -> artifactKind != CodegenMetadataArtifactKind.METADATA_SNAPSHOT }) {
            val transportDefaults = exportSettings.toGenericGenerationSettings().toKspTransportDefaults()
            exportSettings.cExposeTransports
                .sortedBy(CodegenMetadataTransportKind::name)
                .forEach { transport ->
                    val logger = MemoryKspLogger()
                    val environment = createMetadataExportEnvironment(exportSettings, transport.toKspTransportKind(), logger)
                    val writer = ModbusExternalCArtifactWriter.from(environment)
                    if (writer == null) {
                        issues +=
                            CodegenMetadataIssueDto(
                                severity = CodegenMetadataIssueSeverity.ERROR,
                                location = "export.${transport.name.lowercase()}",
                                message = "无法初始化外部 C 产物写入器，请检查 C 工程目录配置。",
                            )
                        issues += logger.toIssues(transport, "export.writer")
                        return@forEach
                    }
                    val transportServices =
                        sourceServices.deriveForTransport(
                            sourceTransport = sourceTransport,
                            targetTransport = transport.toCodegenTransportKind(),
                        )
                    val externalFiles = mutableListOf<File>()
                    buildExternalArtifacts(
                        artifactKinds = exportSettings.artifactKinds,
                        transport = transport.toKspTransportKind(),
                        services = transportServices,
                        transportDefaults = transportDefaults,
                    ).forEach { (artifactKind, artifacts) ->
                        val artifactLogStart = logger.size()
                        artifacts.forEach { artifact ->
                            writer.writeIfSupported(artifact, logger)?.let { target ->
                                generatedArtifacts +=
                                    CodegenGeneratedArtifactDto(
                                        artifactKind = artifactKind,
                                        transport = transport,
                                        path = target.absolutePath,
                                    )
                                externalFiles += target
                            }
                        }
                        issues += logger.toIssues(transport, "export.$artifactKind", artifactLogStart)
                    }
                    val syncLogStart = logger.size()
                    projectSyncResults +=
                        runProjectSyncTools(
                            environment = environment,
                            transport = transport.toKspTransportKind(),
                            firmwareSync = exportSettings.firmwareSync,
                            externalSourceFiles = externalFiles,
                            logger = logger,
                        )
                    issues += logger.toIssues(transport, "export.sync", syncLogStart)
                }
        }

        val summaryParts =
            buildList {
                if (metadataSnapshots.isNotEmpty()) {
                    add("metadata snapshot ${metadataSnapshots.size} 项")
                }
                if (generatedArtifacts.isNotEmpty()) {
                    add("外部产物 ${generatedArtifacts.size} 个文件")
                }
                if (projectSyncResults.isNotEmpty()) {
                    add("工程同步 ${projectSyncResults.size} 项")
                }
            }
        return CodegenMetadataExportResultDto(
            contextId = contextId,
            message = "已完成 ${summaryParts.joinToString("，").ifBlank { "导出" }}。",
            metadataSnapshots = metadataSnapshots,
            generatedArtifacts = generatedArtifacts.distinctBy { artifact -> "${artifact.artifactKind}:${artifact.transport}:${artifact.path}" },
            projectSyncResults = projectSyncResults,
            issues = issues.distinctBy { issue -> "${issue.severity}:${issue.location}:${issue.message}" },
        )
    }

    /**
     * 处理generate。
     *
     * @param context 上下文。
     */
    fun generate(
        context: CodegenContextDetailDto,
    ): GenerateContractsResponseDto {
        val normalized = context.normalizeGenericDetail()
        val exportResult = export(normalized, normalized.toMetadataDraft(normalized.availableContextDefinitions).exportSettings)
        return GenerateContractsResponseDto(
            contextId = exportResult.contextId,
            generatedFiles =
                (
                    exportResult.generatedArtifacts.map(CodegenGeneratedArtifactDto::path) +
                        exportResult.projectSyncResults.mapNotNull(CodegenProjectSyncResultDto::filePath)
                ).sorted(),
            message = exportResult.message,
        )
    }

    private fun syncMetadataSnapshotSelections(
        contextId: Long,
        selectedTransports: Set<CodegenMetadataTransportKind>,
    ) {
        val deselectedTransports =
            CodegenMetadataTransportKind.entries
                .filterNot { transport -> transport in selectedTransports }
                .map { transport -> transport.toCodegenTransportKind().transportId }
        if (deselectedTransports.isEmpty()) {
            return
        }
        dataSource.connection.use { connection ->
            connection.autoCommit = false
            try {
                val placeholders = deselectedTransports.joinToString(",") { "?" }
                connection.prepareStatement(
                    """
                    UPDATE $METADATA_TABLE
                    SET selected = 0
                    WHERE context_id = ?
                      AND transport IN ($placeholders)
                    """.trimIndent(),
                ).use { statement ->
                    statement.setLong(1, contextId)
                    deselectedTransports.forEachIndexed { index, transportId ->
                        statement.setString(index + 2, transportId)
                    }
                    statement.executeUpdate()
                }
                connection.commit()
            } catch (throwable: Throwable) {
                connection.rollback()
                throw throwable
            } finally {
                connection.autoCommit = true
            }
        }
    }

    private fun buildMetadataSnapshotQueryHint(
        transport: CodegenMetadataTransportKind,
    ): String =
        """
        SELECT payload
        FROM $METADATA_TABLE
        WHERE consumer_target = 'MCU_CONSOLE'
          AND enabled = 1
          AND selected = 1
          AND transport = '${transport.name.lowercase()}'
        ORDER BY updated_at DESC
        LIMIT 1
        """.trimIndent()

    private fun buildExternalArtifacts(
        artifactKinds: Set<CodegenMetadataArtifactKind>,
        transport: KspTransportKind,
        services: List<ModbusServiceModel>,
        transportDefaults: site.addzero.device.protocol.modbus.ksp.core.ModbusTransportDefaults,
    ): List<Pair<CodegenMetadataArtifactKind, List<KspGeneratedArtifact>>> {
        if (services.isEmpty()) {
            return emptyList()
        }
        val kspServices = services.toKspServiceModels()
        return buildList {
            if (CodegenMetadataArtifactKind.C_SERVICE_CONTRACT in artifactKinds) {
                add(
                    CodegenMetadataArtifactKind.C_SERVICE_CONTRACT to
                        kspServices.flatMap { service ->
                            ModbusArtifactRenderer.renderServiceContractArtifacts(service, transportDefaults)
                        },
                )
            }
            if (CodegenMetadataArtifactKind.C_TRANSPORT_CONTRACT in artifactKinds) {
                add(
                    CodegenMetadataArtifactKind.C_TRANSPORT_CONTRACT to
                        ModbusArtifactRenderer.renderTransportContractArtifacts(
                            transport = transport,
                            services = services.toKspServiceModels(),
                            transportDefaults = transportDefaults,
                        ),
                )
            }
            if (CodegenMetadataArtifactKind.MARKDOWN_PROTOCOL in artifactKinds) {
                add(
                    CodegenMetadataArtifactKind.MARKDOWN_PROTOCOL to
                        kspServices.flatMap { service ->
                            ModbusArtifactRenderer.renderMarkdownArtifacts(service, transportDefaults)
                        },
                )
            }
        }
    }

    /**
     * 处理render。
     *
     * @param context 上下文。
     * @param workspaceRoot workspace根目录。
     */
    internal fun render(
        context: CodegenContextDetailDto,
        workspaceRoot: Path,
    ): RenderedContracts {
        @Suppress("UNUSED_VARIABLE")
        val ignoredWorkspaceRoot = workspaceRoot
        val services = context.toModbusServices()
        val artifacts =
            ModbusKotlinContractGenerator.render(
                ModbusKotlinContractGenerationRequest(
                    services = services,
                    fileHeader = GENERATED_MARKER,
                    dtoCustomizations = buildDtoCustomizations(context),
                ),
            )
        val artifactsByFile = artifacts.associateBy(GeneratedArtifact::fileName)
        val registerDtos =
            artifacts
                .filter { artifact -> artifact.fileName.endsWith("Registers") }
                .associate { artifact ->
                    "${artifact.fileName}.kt" to artifact.content.normalizeGeneratedKotlin()
                }
        return RenderedContracts(
            deviceApi =
                artifactsByFile["DeviceApi"]?.content?.normalizeGeneratedKotlin()
                    ?: renderEmptyInterface("DeviceApi"),
            deviceWriteApi =
                artifactsByFile["DeviceWriteApi"]?.content?.normalizeGeneratedKotlin()
                    ?: renderEmptyInterface("DeviceWriteApi"),
            registerDtos = registerDtos,
            metadataPayload = ModbusMetadataJsonCodec.encodeServices(services),
            services = services,
            transport = context.modbusTransport(),
        )
    }

    /**
     * 构建数据传输对象customizations。
     *
     * @param context 上下文。
     */
    private fun buildDtoCustomizations(
        context: CodegenContextDetailDto,
    ): Map<String, ModbusDtoCustomization> {
        return context.toModbusSpecs()
            .filter { schema -> schema.direction == ModbusSchemaDirection.READ && !schema.modelName.isNullOrBlank() }
            .associate { schema ->
                val modelName = requireNotNull(schema.modelName)
                "$MCU_DEVICE_PACKAGE.${modelName}Registers" to
                    ModbusDtoCustomization(
                        summary = schema.description.cleanDocSummary() ?: schema.name,
                        propertyDocs =
                            schema.fields.associate { field ->
                                field.propertyName to (field.description.cleanDocSummary() ?: field.name)
                            },
                    )
            }
    }

    /**
     * 写入rendered文件。
     *
     * @param rendered 渲染结果。
     * @param settings 设置。
     */
    private fun writeRenderedFiles(
        rendered: RenderedContracts,
        settings: ResolvedGenerationSettings,
    ): List<String> {
        settings.serverPackageDir.createDirectories()
        settings.sharedPackageDir.createDirectories()
        writeFile(settings.serverPackageDir.resolve("DeviceApi.kt"), rendered.deviceApi)
        writeFile(settings.serverPackageDir.resolve("DeviceWriteApi.kt"), rendered.deviceWriteApi)
        settings.sharedPackageDir.listDirectoryEntries("*.kt").forEach { existing ->
            if (existing.name.endsWith("Registers.kt")) {
                existing.deleteIfExists()
            }
        }
        rendered.registerDtos.forEach { (fileName, content) ->
            writeFile(settings.sharedPackageDir.resolve(fileName), content)
        }
        return buildList {
            add(settings.serverPackageDir.resolve("DeviceApi.kt").toAbsolutePath().normalize().toString())
            add(settings.serverPackageDir.resolve("DeviceWriteApi.kt").toAbsolutePath().normalize().toString())
            rendered.registerDtos.keys.sorted().forEach { fileName ->
                add(settings.sharedPackageDir.resolve(fileName).toAbsolutePath().normalize().toString())
            }
        }
    }

    /**
     * 写入传输产物。
     *
     * @param rendered 渲染结果。
     * @param settings 设置。
     */
    private fun writeTransportArtifacts(
        rendered: RenderedContracts,
        settings: ResolvedGenerationSettings,
    ): List<String> {
        val primaryServices = rendered.services.toKspServiceModels()
        val primaryTransport = rendered.transport.toArtifactKspTransportKind()
        val generatedFiles = mutableListOf<String>()
        cleanupGeneratedPackageDir(settings.gatewayOutputRoot, primaryTransport.generatedPackage.replace('.', '/'))
        val serverRouteMode =
            if (settings.springRouteOutputRoot == null) {
                ModbusServerRouteMode.DIRECT_KTOR
            } else {
                ModbusServerRouteMode.SPRING_SOURCE
            }
        generatedFiles +=
            writeKspArtifactsWithPaths(
                settings.gatewayOutputRoot,
                ModbusArtifactRenderer.renderServerArtifacts(
                    transport = primaryTransport,
                    services = primaryServices,
                    transportDefaults = settings.transportDefaults,
                    serverRouteMode = serverRouteMode,
                ),
            )

        settings.springRouteOutputRoot?.let { outputRoot ->
            cleanupGeneratedPackageDir(outputRoot, primaryTransport.generatedPackage.replace('.', '/'))
            generatedFiles +=
                writeKspArtifactsWithPaths(
                    outputRoot,
                    ModbusArtifactRenderer.renderSpringRouteSourceArtifacts(primaryTransport, primaryServices),
                )
        }

        if (settings.apiClientOutputRoot != null && settings.apiClientPackageName != null) {
            cleanupGeneratedPackageDir(settings.apiClientOutputRoot, settings.apiClientPackageName.replace('.', '/'))
            generatedFiles +=
                writeKspArtifactsWithPaths(
                    settings.apiClientOutputRoot,
                    ModbusArtifactRenderer.renderKtorfitClientArtifacts(
                        transport = primaryTransport,
                        services = primaryServices,
                        packageName = settings.apiClientPackageName,
                    ),
                )
        }

        generatedFiles += writeExternalArtifacts(rendered, settings)

        return generatedFiles.sorted()
    }

    /**
     * 写入外部产物。
     *
     * @param rendered 渲染结果。
     * @param settings 设置。
     */
    private fun writeExternalArtifacts(
        rendered: RenderedContracts,
        settings: ResolvedGenerationSettings,
    ): List<String> {
        if (settings.cOutputRoot == null && settings.markdownOutputRoot == null) {
            return emptyList()
        }
        val generatedFiles = mutableListOf<String>()
        EXTERNAL_ARTIFACT_TRANSPORTS.forEach { transport ->
            val services =
                rendered.services
                    .deriveForTransport(sourceTransport = rendered.transport, targetTransport = transport)
                    .toKspServiceModels()
            val kspTransport = transport.toArtifactKspTransportKind()

            settings.cOutputRoot?.let { outputRoot ->
                cleanupGeneratedPackageDir(outputRoot, "generated/modbus/${transport.transportId}")
                val cArtifacts =
                    buildList {
                        services.forEach { service ->
                            addAll(ModbusArtifactRenderer.renderServiceContractArtifacts(service, settings.transportDefaults))
                            addAll(
                                ModbusArtifactRenderer
                                    .renderMarkdownArtifacts(service, settings.transportDefaults)
                                    .filter { artifact -> artifact.extensionName == "c" },
                            )
                        }
                        addAll(
                            ModbusArtifactRenderer.renderTransportContractArtifacts(
                                transport = kspTransport,
                                services = services,
                                transportDefaults = settings.transportDefaults,
                            ),
                        )
                    }
                generatedFiles += writeKspArtifactsWithPaths(outputRoot, cArtifacts)
            }

            settings.markdownOutputRoot?.let { outputRoot ->
                cleanupGeneratedMarkdownArtifacts(outputRoot, transport)
                val markdownArtifacts =
                    services.flatMap { service ->
                        ModbusArtifactRenderer
                            .renderMarkdownArtifacts(service, settings.transportDefaults)
                            .filter { artifact -> artifact.extensionName == "md" }
                    }
                generatedFiles += writeKspArtifactsWithPaths(outputRoot, markdownArtifacts)
            }
        }
        return generatedFiles
    }

    /**
     * 处理upsertmetadata快照。
     *
     * @param context 上下文。
     * @param rendered 渲染结果。
     */
    private fun upsertMetadataSnapshot(
        context: CodegenContextDetailDto,
        rendered: RenderedContracts,
    ) {
        upsertMetadataSnapshot(
            context = context,
            transport = rendered.transport,
            payload = rendered.metadataPayload,
        )
    }

    private fun upsertMetadataSnapshot(
        context: CodegenContextDetailDto,
        transport: ModbusTransportKind,
        payload: String,
    ) {
        dataSource.connection.use { connection ->
            connection.autoCommit = false
            try {
                val now = Instant.now()
                connection.prepareStatement(
                    """
                    UPDATE $METADATA_TABLE
                    SET selected = 0
                    WHERE consumer_target = ? AND transport = ?
                    """.trimIndent(),
                ).use { statement ->
                    statement.setString(1, context.consumerTarget.name)
                    statement.setString(2, transport.transportId)
                    statement.executeUpdate()
                }
                val insertSql =
                    """
                    INSERT INTO $METADATA_TABLE (
                        context_id,
                        context_code,
                        context_name,
                        enabled,
                        consumer_target,
                        protocol_template_code,
                        transport,
                        selected,
                        payload,
                        updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """.trimIndent()
                connection.prepareStatement(insertSql.appendUpsertClause(connection)).use { statement ->
                    statement.setLong(1, requireNotNull(context.id))
                    statement.setString(2, context.code)
                    statement.setString(3, context.name)
                    statement.setInt(4, if (context.enabled) 1 else 0)
                    statement.setString(5, context.consumerTarget.name)
                    statement.setString(6, context.protocolTemplateCode.orEmpty())
                    statement.setString(7, transport.transportId)
                    statement.setInt(8, 1)
                    statement.setString(9, payload)
                    statement.setUpdatedAt(10, connection, now)
                    statement.executeUpdate()
                }
                connection.commit()
            } catch (throwable: Throwable) {
                connection.rollback()
                throw throwable
            } finally {
                connection.autoCommit = true
            }
        }
    }

    /**
     * 处理renderemptyinterface。
     *
     * @param interfaceSimpleName interfacesimple名称。
     */
    private fun renderEmptyInterface(
        interfaceSimpleName: String,
    ): String =
        """
        // $GENERATED_MARKER
        package $MCU_DEVICE_PACKAGE

        interface $interfaceSimpleName
        """.trimIndent().normalizeGeneratedKotlin()

    /**
     * 写入file。
     *
     * @param target 目标。
     * @param content content。
     */
    private fun writeFile(
        target: Path,
        content: String,
    ) {
        target.parent?.createDirectories()
        Files.writeString(
            target,
            content,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING,
            StandardOpenOption.WRITE,
        )
    }
}

/**
 * 表示renderedcontracts。
 *
 * @property deviceApi 设备API。
 * @property deviceWriteApi 设备writeAPI。
 * @property registerDtos 寄存器数据传输对象。
 * @property metadataPayload 元数据载荷。
 * @property services 服务。
 * @property transport 传输。
 */
internal data class RenderedContracts(
    val deviceApi: String,
    val deviceWriteApi: String,
    val registerDtos: Map<String, String>,
    val metadataPayload: String,
    val services: List<ModbusServiceModel>,
    val transport: ModbusTransportKind,
)

/**
 * 处理代码生成上下文详情数据传输对象。
 */
private fun CodegenContextDetailDto.toModbusServices(): List<ModbusServiceModel> {
    val transport = modbusTransport()
    val sortedSchemas = toModbusSpecs().sortedBy(ModbusSchemaSpec::sortIndex)
    val services = mutableListOf<ModbusServiceModel>()

    val readOperations =
        sortedSchemas
            .filter { schema -> schema.direction == ModbusSchemaDirection.READ }
            .map { schema -> schema.toReadOperation(transport) }
            .let(ModbusContractDefaultsResolver::resolveOperationIdsAndQuantities)
    if (readOperations.isNotEmpty()) {
        services +=
            ModbusServiceModel(
                interfacePackage = MCU_DEVICE_PACKAGE,
                interfaceSimpleName = "DeviceApi",
                interfaceQualifiedName = "$MCU_DEVICE_PACKAGE.DeviceApi",
                serviceId = ModbusContractDefaultsResolver.defaultServiceId("DeviceApi"),
                summary = name,
                basePath = "/api/modbus",
                transport = transport,
                doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
                operations = readOperations,
            )
    }

    val writeOperations =
        sortedSchemas
            .filter { schema -> schema.direction == ModbusSchemaDirection.WRITE }
            .map { schema -> schema.toWriteOperation(transport) }
            .let(ModbusContractDefaultsResolver::resolveOperationIdsAndQuantities)
    if (writeOperations.isNotEmpty()) {
        services +=
            ModbusServiceModel(
                interfacePackage = MCU_DEVICE_PACKAGE,
                interfaceSimpleName = "DeviceWriteApi",
                interfaceQualifiedName = "$MCU_DEVICE_PACKAGE.DeviceWriteApi",
                serviceId = ModbusContractDefaultsResolver.defaultServiceId("DeviceWriteApi"),
                summary = name,
                basePath = "/api/modbus",
                transport = transport,
                doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
                operations = writeOperations,
            )
    }

    return services
}

/**
 * 处理modbus结构spec。
 *
 * @param transport 传输。
 */
private fun ModbusSchemaSpec.toReadOperation(
    transport: ModbusTransportKind,
): ModbusOperationModel {
    val resolvedModelName = requireNotNull(modelName) { "Validated READ schema requires modelName." }
    return ModbusOperationModel(
        methodName = methodName,
        operationId = "",
        functionCodeName = functionCode.name,
        address = baseAddress,
        quantity = -1,
        requestClassName = buildRequestClassName("DeviceApi", transport, methodName),
        requestQualifiedName = buildRequestQualifiedName("DeviceApi", transport, methodName),
        parameters = emptyList(),
        returnType =
            ModbusReturnTypeModel(
                qualifiedName = "$MCU_DEVICE_PACKAGE.${resolvedModelName}Registers",
                simpleName = "${resolvedModelName}Registers",
                kind = ModbusReturnKind.DTO,
                docSummary = description.cleanDocSummary() ?: name,
                properties = fields.sortedBy(ModbusFieldSpec::sortIndex).map(ModbusFieldSpec::toPropertyModel),
            ),
        doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
    )
}

/**
 * 处理modbus结构spec。
 *
 * @param transport 传输。
 */
private fun ModbusSchemaSpec.toWriteOperation(
    transport: ModbusTransportKind,
): ModbusOperationModel =
    ModbusOperationModel(
        methodName = methodName,
        operationId = "",
        functionCodeName = functionCode.name,
        address = baseAddress,
        quantity = -1,
        requestClassName = buildRequestClassName("DeviceWriteApi", transport, methodName),
        requestQualifiedName = buildRequestQualifiedName("DeviceWriteApi", transport, methodName),
        parameters = fields.sortedBy(ModbusFieldSpec::sortIndex).mapIndexed { index, field -> field.toParameterModel(index) },
        returnType =
            ModbusReturnTypeModel(
                qualifiedName = "site.addzero.device.protocol.modbus.model.ModbusCommandResult",
                simpleName = "ModbusCommandResult",
                kind = ModbusReturnKind.COMMAND_RESULT,
            ),
        doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
    )

/**
 * 处理modbus字段spec。
 */
private fun ModbusFieldSpec.toPropertyModel(): ModbusPropertyModel =
    ModbusPropertyModel(
        name = propertyName,
        qualifiedType = transportType.kotlinQualifiedTypeName(),
        valueKind = transportType.valueKind(),
        field =
            ModbusFieldModel(
                codecName = transportType.codecName(),
                registerOffset = registerOffset,
                bitOffset = bitOffset,
                length = length,
                registerWidth = transportType.registerWidth(length),
            ),
        doc = description.cleanDocSummary() ?: name,
    )

/**
 * 处理modbus字段spec。
 *
 * @param order 顺序。
 */
private fun ModbusFieldSpec.toParameterModel(order: Int): ModbusParameterModel =
    ModbusParameterModel(
        name = propertyName,
        qualifiedType = transportType.kotlinQualifiedTypeName(),
        valueKind = transportType.valueKind(),
        order = order,
        codecName = transportType.codecName(),
        registerOffset = registerOffset,
        bitOffset = bitOffset,
        registerWidth = transportType.registerWidth(length),
        length = length,
        doc = description.cleanDocSummary() ?: name,
    )

/**
 * 处理代码生成上下文详情数据传输对象。
 */
private fun CodegenContextDetailDto.modbusTransport(): ModbusTransportKind =
    when (protocolTemplateCode) {
        "MODBUS_TCP_CLIENT" -> ModbusTransportKind.TCP
        else -> ModbusTransportKind.RTU
    }

/**
 * 处理列表。
 *
 * @param sourceTransport 来源传输。
 * @param targetTransport 目标传输。
 */
private fun List<ModbusServiceModel>.deriveForTransport(
    sourceTransport: ModbusTransportKind,
    targetTransport: ModbusTransportKind,
): List<ModbusServiceModel> =
    map { service ->
        service.deriveForTransport(sourceTransport = sourceTransport, targetTransport = targetTransport)
    }

/**
 * 处理modbus服务模型。
 *
 * @param sourceTransport 来源传输。
 * @param targetTransport 目标传输。
 */
private fun ModbusServiceModel.deriveForTransport(
    sourceTransport: ModbusTransportKind,
    targetTransport: ModbusTransportKind,
): ModbusServiceModel {
    if (sourceTransport == targetTransport) {
        return this
    }
    return copy(
        transport = targetTransport,
        operations =
            operations.map { operation ->
                operation.copy(
                    requestClassName = operation.requestClassName.rewriteTransportToken(sourceTransport, targetTransport),
                    requestQualifiedName = operation.requestQualifiedName.rewriteTransportToken(sourceTransport, targetTransport),
                )
            },
        workflows =
            workflows.map { workflow ->
                workflow.copy(
                    requestClassName = workflow.requestClassName.rewriteTransportToken(sourceTransport, targetTransport),
                    requestQualifiedName = workflow.requestQualifiedName.rewriteTransportToken(sourceTransport, targetTransport),
                )
            },
    )
}

/**
 * 处理string。
 *
 * @param sourceTransport 来源传输。
 * @param targetTransport 目标传输。
 */
private fun String.rewriteTransportToken(
    sourceTransport: ModbusTransportKind,
    targetTransport: ModbusTransportKind,
): String {
    if (sourceTransport == targetTransport) {
        return this
    }
    val sourceToken = sourceTransport.transportId.replaceFirstChar(Char::uppercase)
    val targetToken = targetTransport.transportId.replaceFirstChar(Char::uppercase)
    return replace(sourceToken, targetToken)
}

/**
 * 构建请求类名。
 *
 * @param interfaceSimpleName interfacesimple名称。
 * @param transport 传输。
 * @param methodName 方法名称。
 */
private fun buildRequestClassName(
    interfaceSimpleName: String,
    transport: ModbusTransportKind,
    methodName: String,
): String {
    val prefix = interfaceSimpleName + transport.transportId.replaceFirstChar(Char::uppercase)
    return prefix + methodName.replaceFirstChar(Char::uppercase) + "Request"
}

/**
 * 构建请求qualified名称。
 *
 * @param interfaceSimpleName interfacesimple名称。
 * @param transport 传输。
 * @param methodName 方法名称。
 */
private fun buildRequestQualifiedName(
    interfaceSimpleName: String,
    transport: ModbusTransportKind,
    methodName: String,
): String =
    "$MCU_DEVICE_PACKAGE.generated.${buildRequestClassName(interfaceSimpleName, transport, methodName)}"

/**
 * 处理modbus传输类型。
 */
private fun ModbusTransportType.codecName(): String =
    when (this) {
        ModbusTransportType.BOOL_COIL -> "BOOL_COIL"
        ModbusTransportType.U16 -> "U16"
        ModbusTransportType.U32_BE -> "U32_BE"
        ModbusTransportType.STRING_ASCII -> "STRING_ASCII"
        ModbusTransportType.STRING_UTF8 -> "STRING_UTF8"
    }

/**
 * 处理modbus传输类型。
 */
private fun ModbusTransportType.valueKind(): ModbusValueKind =
    when (this) {
        ModbusTransportType.BOOL_COIL -> ModbusValueKind.BOOLEAN
        ModbusTransportType.U16,
        ModbusTransportType.U32_BE -> ModbusValueKind.INT
        ModbusTransportType.STRING_ASCII,
        ModbusTransportType.STRING_UTF8 -> ModbusValueKind.STRING
    }

/**
 * 处理modbus传输类型。
 */
private fun ModbusTransportType.kotlinQualifiedTypeName(): String =
    when (this) {
        ModbusTransportType.BOOL_COIL -> "kotlin.Boolean"
        ModbusTransportType.U16,
        ModbusTransportType.U32_BE -> "kotlin.Int"
        ModbusTransportType.STRING_ASCII,
        ModbusTransportType.STRING_UTF8 -> "kotlin.String"
    }

/**
 * 处理string。
 */
internal fun String.normalizeGeneratedKotlin(): String =
    lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"

/**
 * 处理string。
 */
internal fun String?.cleanDocSummary(): String? =
    this?.trim()?.takeIf(String::isNotBlank)

/**
 * 处理string。
 *
 * @param connection 数据库连接。
 */
private fun String.appendUpsertClause(
    connection: Connection,
): String =
    when {
        connection.isSqlite() ->
            this +
                """

                ON CONFLICT(context_id, transport) DO UPDATE SET
                    context_code = excluded.context_code,
                    context_name = excluded.context_name,
                    enabled = excluded.enabled,
                    consumer_target = excluded.consumer_target,
                    protocol_template_code = excluded.protocol_template_code,
                    selected = excluded.selected,
                    payload = excluded.payload,
                    updated_at = excluded.updated_at
                """.trimIndent()

        else -> error("Unsupported metadata snapshot database: ${connection.metaData.databaseProductName}")
    }

/**
 * 处理preparedstatement。
 *
 * @param index 序号。
 * @param connection 数据库连接。
 * @param instant 时间点。
 */
private fun PreparedStatement.setUpdatedAt(
    index: Int,
    connection: Connection,
    instant: Instant,
) {
    when {
        connection.isSqlite() -> setLong(index, instant.toEpochMilli())
        else -> error("Unsupported metadata snapshot database: ${connection.metaData.databaseProductName}")
    }
}

private fun Connection.isSqlite(): Boolean =
    metaData.databaseProductName.contains("sqlite", ignoreCase = true) ||
        metaData.url.contains(":sqlite:", ignoreCase = true)

private fun CodegenMetadataTransportKind.toCodegenTransportKind(): ModbusTransportKind =
    when (this) {
        CodegenMetadataTransportKind.RTU -> ModbusTransportKind.RTU
        CodegenMetadataTransportKind.TCP -> ModbusTransportKind.TCP
        CodegenMetadataTransportKind.MQTT -> ModbusTransportKind.MQTT
    }

private fun CodegenMetadataTransportKind.toKspTransportKind(): KspTransportKind =
    when (this) {
        CodegenMetadataTransportKind.RTU -> KspTransportKind.RTU
        CodegenMetadataTransportKind.TCP -> KspTransportKind.TCP
        CodegenMetadataTransportKind.MQTT -> KspTransportKind.MQTT
    }
