package site.addzero.kcloud.plugins.codegencontext.codegen_context.service

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.sql.Connection
import java.sql.PreparedStatement
import java.time.Instant
import javax.sql.DataSource
import kotlin.io.path.createDirectories
import kotlin.io.path.deleteIfExists
import kotlin.io.path.exists
import kotlin.io.path.isDirectory
import kotlin.io.path.listDirectoryEntries
import kotlin.io.path.name
import org.koin.core.annotation.Single
import site.addzero.device.protocol.modbus.codegen.ModbusContractDefaultsResolver
import site.addzero.device.protocol.modbus.codegen.ModbusDtoCustomization
import site.addzero.device.protocol.modbus.codegen.ModbusKotlinContractGenerationRequest
import site.addzero.device.protocol.modbus.codegen.ModbusKotlinContractGenerator
import site.addzero.device.protocol.modbus.codegen.ModbusMetadataJsonCodec
import site.addzero.device.protocol.modbus.codegen.model.GeneratedArtifact
import site.addzero.device.protocol.modbus.codegen.model.ModbusDocModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusFieldModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusOperationModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusParameterModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusPropertyModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusReturnTypeModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusServiceModel
import site.addzero.device.protocol.modbus.codegen.model.ModbusTransportKind
import site.addzero.device.protocol.modbus.codegen.model.ModbusValueKind
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenContextDetailDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenFieldDto
import site.addzero.kcloud.plugins.codegencontext.api.context.CodegenSchemaDto
import site.addzero.kcloud.plugins.codegencontext.api.context.GenerateContractsResponseDto
import site.addzero.kcloud.plugins.codegencontext.codegen_context.routes.common.BusinessValidationException
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenConsumerTarget
import site.addzero.kcloud.plugins.codegencontext.model.enums.CodegenTransportType

private const val GENERATED_MARKER = "Generated by codegen-context. DO NOT EDIT."
private const val MCU_DEVICE_PACKAGE = "site.addzero.kcloud.plugins.mcuconsole.modbus.device"
private const val METADATA_TABLE = "codegen_context_modbus_contract"

@Single
class CodegenContextContractGenerator(
    private val dataSource: DataSource,
) {
    fun generate(
        context: CodegenContextDetailDto,
    ): GenerateContractsResponseDto {
        if (context.consumerTarget != CodegenConsumerTarget.MCU_CONSOLE) {
            throw BusinessValidationException("Only MCU_CONSOLE is supported in V1.")
        }
        val contextId = context.id ?: throw BusinessValidationException("Context id is required for generation.")
        val roots = locateGeneratedRoots()
        val rendered = render(context, roots.workspaceRoot)
        writeRenderedFiles(rendered, roots)
        upsertMetadataSnapshot(context, rendered)
        val generatedFiles =
            buildList {
                add(roots.serverPackageDir.resolve("DeviceApi.kt").toAbsolutePath().normalize().toString())
                add(roots.serverPackageDir.resolve("DeviceWriteApi.kt").toAbsolutePath().normalize().toString())
                rendered.registerDtos.keys.sorted().forEach { fileName ->
                    add(roots.sharedPackageDir.resolve(fileName).toAbsolutePath().normalize().toString())
                }
            }
        return GenerateContractsResponseDto(
            contextId = contextId,
            generatedFiles = generatedFiles,
            message = "Generated ${generatedFiles.size} contract artifacts for ${context.code}.",
        )
    }

    internal fun render(
        context: CodegenContextDetailDto,
        workspaceRoot: Path,
    ): RenderedContracts {
        val services = context.toModbusServices()
        val dtoCustomizations = buildDtoCustomizations(context, workspaceRoot)
        val artifacts =
            ModbusKotlinContractGenerator.render(
                ModbusKotlinContractGenerationRequest(
                    services = services,
                    fileHeader = GENERATED_MARKER,
                    dtoCustomizations = dtoCustomizations,
                ),
            )
        val artifactsByFile = artifacts.associateBy { artifact -> artifact.fileName }
        val registerDtos =
            artifacts
                .filter { artifact -> artifact.fileName.endsWith("Registers") }
                .associate { artifact -> "${artifact.fileName}.kt" to artifact.content.normalizeGeneratedKotlin() }
        return RenderedContracts(
            deviceApi = requireArtifact(artifactsByFile, "DeviceApi"),
            deviceWriteApi = requireArtifact(artifactsByFile, "DeviceWriteApi"),
            registerDtos = registerDtos,
            metadataPayload = ModbusMetadataJsonCodec.encodeServices(services),
            transportId = context.modbusTransport().transportId,
        )
    }

    private fun requireArtifact(
        artifactsByFile: Map<String, GeneratedArtifact>,
        fileName: String,
    ): String {
        return artifactsByFile[fileName]
            ?.content
            ?.normalizeGeneratedKotlin()
            ?: throw BusinessValidationException("Missing generated Kotlin artifact: $fileName")
    }

    private fun buildDtoCustomizations(
        context: CodegenContextDetailDto,
        workspaceRoot: Path,
    ): Map<String, ModbusDtoCustomization> {
        return context.schemas
            .filter { schema -> schema.direction.name == "READ" && !schema.modelName.isNullOrBlank() }
            .associate { schema ->
                val modelName = requireNotNull(schema.modelName)
                val dtoQualifiedName = "$MCU_DEVICE_PACKAGE.${modelName}Registers"
                dtoQualifiedName to
                    ModbusDtoCustomization(
                        summary = schema.description.cleanDocSummary() ?: schema.name,
                        propertyDocs =
                            schema.fields.associate { field ->
                                field.propertyName to
                                    (
                                        field.description.cleanDocSummary()
                                            ?: field.name
                                        )
                            },
                    )
            }
    }

    private fun locateGeneratedRoots(): GeneratedRoots {
        val workspaceRoot = locateWorkspaceRoot()
        val serverRoot = workspaceRoot.resolve("apps/kcloud/plugins/mcu-console/server/generated/jvmMain/kotlin")
        val sharedRoot = workspaceRoot.resolve("apps/kcloud/plugins/mcu-console/shared/generated/commonMain/kotlin")
        val serverPackageDir = safeResolve(serverRoot, "site/addzero/kcloud/plugins/mcuconsole/modbus/device")
        val sharedPackageDir = safeResolve(sharedRoot, "site/addzero/kcloud/plugins/mcuconsole/modbus/device")
        return GeneratedRoots(
            workspaceRoot = workspaceRoot,
            serverPackageDir = serverPackageDir,
            sharedPackageDir = sharedPackageDir,
        )
    }

    private fun locateWorkspaceRoot(): Path {
        val overrideRoot = System.getProperty("codegen.context.repoRoot")?.takeIf(String::isNotBlank)
        var current =
            Path.of(overrideRoot ?: System.getProperty("user.dir"))
                .toAbsolutePath()
                .normalize()
        while (true) {
            if (current.resolve("settings.gradle.kts").exists() &&
                current.resolve("apps/kcloud/plugins/mcu-console").isDirectory()
            ) {
                return current
            }
            current = current.parent ?: break
        }
        throw BusinessValidationException("Unable to locate the kmp-aio workspace root.")
    }

    private fun safeResolve(
        root: Path,
        relative: String,
    ): Path {
        val normalizedRoot = root.toAbsolutePath().normalize()
        val target = normalizedRoot.resolve(relative).normalize()
        if (!target.startsWith(normalizedRoot)) {
            throw BusinessValidationException("Refuse to write outside generated roots: $target")
        }
        return target
    }

    private fun writeRenderedFiles(
        rendered: RenderedContracts,
        roots: GeneratedRoots,
    ) {
        roots.serverPackageDir.createDirectories()
        roots.sharedPackageDir.createDirectories()
        writeFile(roots.serverPackageDir.resolve("DeviceApi.kt"), rendered.deviceApi)
        writeFile(roots.serverPackageDir.resolve("DeviceWriteApi.kt"), rendered.deviceWriteApi)
        roots.sharedPackageDir.listDirectoryEntries("*.kt").forEach { existing ->
            if (existing.name.endsWith("Registers.kt")) {
                existing.deleteIfExists()
            }
        }
        rendered.registerDtos.forEach { (fileName, content) ->
            writeFile(roots.sharedPackageDir.resolve(fileName), content)
        }
    }

    private fun upsertMetadataSnapshot(
        context: CodegenContextDetailDto,
        rendered: RenderedContracts,
    ) {
        dataSource.connection.use { connection ->
            connection.autoCommit = false
            try {
                val now = Instant.now()
                connection.prepareStatement(
                    """
                    UPDATE $METADATA_TABLE
                    SET selected = 0
                    WHERE consumer_target = ? AND transport = ?
                    """.trimIndent(),
                ).use { statement ->
                    statement.setString(1, context.consumerTarget.name)
                    statement.setString(2, rendered.transportId)
                    statement.executeUpdate()
                }
                val insertSql =
                    """
                    INSERT INTO $METADATA_TABLE (
                        context_id,
                        context_code,
                        context_name,
                        enabled,
                        consumer_target,
                        protocol_template_code,
                        transport,
                        selected,
                        payload,
                        updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """.trimIndent()
                connection.prepareStatement(insertSql.appendUpsertClause(connection)).use { statement ->
                    statement.setLong(1, requireNotNull(context.id))
                    statement.setString(2, context.code)
                    statement.setString(3, context.name)
                    statement.setInt(4, if (context.enabled) 1 else 0)
                    statement.setString(5, context.consumerTarget.name)
                    statement.setString(6, context.protocolTemplateCode.orEmpty())
                    statement.setString(7, rendered.transportId)
                    statement.setInt(8, 1)
                    statement.setString(9, rendered.metadataPayload)
                    statement.setUpdatedAt(10, connection, now)
                    statement.executeUpdate()
                }
                connection.commit()
            } catch (throwable: Throwable) {
                connection.rollback()
                throw throwable
            } finally {
                connection.autoCommit = true
            }
        }
    }

    private fun writeFile(
        target: Path,
        content: String,
    ) {
        target.parent?.createDirectories()
        Files.writeString(
            target,
            content,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING,
            StandardOpenOption.WRITE,
        )
    }
}

internal data class RenderedContracts(
    val deviceApi: String,
    val deviceWriteApi: String,
    val registerDtos: Map<String, String>,
    val metadataPayload: String,
    val transportId: String,
)

internal data class GeneratedRoots(
    val workspaceRoot: Path,
    val serverPackageDir: Path,
    val sharedPackageDir: Path,
)

internal data class ApiModelDoc(
    val classSummary: String?,
    val propertyDocs: Map<String, String>,
)

private fun CodegenContextDetailDto.toModbusServices(): List<ModbusServiceModel> {
    val transport = modbusTransport()
    val sortedSchemas = schemas.sortedBy(CodegenSchemaDto::sortIndex)
    val services = mutableListOf<ModbusServiceModel>()

    val readOperations =
        sortedSchemas
            .filter { schema -> schema.direction.name == "READ" }
            .map { schema -> schema.toReadOperation(transport) }
            .let(ModbusContractDefaultsResolver::resolveOperationIdsAndQuantities)
    if (readOperations.isNotEmpty()) {
        services +=
            ModbusServiceModel(
                interfacePackage = MCU_DEVICE_PACKAGE,
                interfaceSimpleName = "DeviceApi",
                interfaceQualifiedName = "$MCU_DEVICE_PACKAGE.DeviceApi",
                serviceId = ModbusContractDefaultsResolver.defaultServiceId("DeviceApi"),
                summary = name,
                basePath = "/api/modbus",
                transport = transport,
                doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
                operations = readOperations,
            )
    }

    val writeOperations =
        sortedSchemas
            .filter { schema -> schema.direction.name == "WRITE" }
            .map { schema -> schema.toWriteOperation(transport) }
            .let(ModbusContractDefaultsResolver::resolveOperationIdsAndQuantities)
    if (writeOperations.isNotEmpty()) {
        services +=
            ModbusServiceModel(
                interfacePackage = MCU_DEVICE_PACKAGE,
                interfaceSimpleName = "DeviceWriteApi",
                interfaceQualifiedName = "$MCU_DEVICE_PACKAGE.DeviceWriteApi",
                serviceId = ModbusContractDefaultsResolver.defaultServiceId("DeviceWriteApi"),
                summary = name,
                basePath = "/api/modbus",
                transport = transport,
                doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
                operations = writeOperations,
            )
    }

    return services
}

private fun CodegenSchemaDto.toReadOperation(
    transport: ModbusTransportKind,
): ModbusOperationModel {
    val resolvedModelName = requireNotNull(modelName) { "Validated READ schema requires modelName." }
    return ModbusOperationModel(
        methodName = methodName,
        operationId = "",
        functionCodeName = functionCode.name,
        address = baseAddress,
        quantity = -1,
        requestClassName = buildRequestClassName("DeviceApi", transport, methodName),
        requestQualifiedName = buildRequestQualifiedName("DeviceApi", transport, methodName),
        parameters = emptyList(),
        returnType =
            ModbusReturnTypeModel(
                qualifiedName = "$MCU_DEVICE_PACKAGE.${resolvedModelName}Registers",
                simpleName = "${resolvedModelName}Registers",
                kind = ModbusReturnKind.DTO,
                docSummary = description.cleanDocSummary() ?: name,
                properties = fields.sortedBy(CodegenFieldDto::sortIndex).map { field -> field.toPropertyModel() },
            ),
        doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
    )
}

private fun CodegenSchemaDto.toWriteOperation(
    transport: ModbusTransportKind,
): ModbusOperationModel {
    return ModbusOperationModel(
        methodName = methodName,
        operationId = "",
        functionCodeName = functionCode.name,
        address = baseAddress,
        quantity = -1,
        requestClassName = buildRequestClassName("DeviceWriteApi", transport, methodName),
        requestQualifiedName = buildRequestQualifiedName("DeviceWriteApi", transport, methodName),
        parameters =
            fields
                .sortedBy(CodegenFieldDto::sortIndex)
                .mapIndexed { index, field -> field.toParameterModel(index) },
        returnType =
            ModbusReturnTypeModel(
                qualifiedName = "site.addzero.device.protocol.modbus.model.ModbusCommandResult",
                simpleName = "ModbusCommandResult",
                kind = ModbusReturnKind.COMMAND_RESULT,
            ),
        doc = ModbusDocModel(summary = description.cleanDocSummary() ?: name),
    )
}

private fun CodegenFieldDto.toPropertyModel(): ModbusPropertyModel =
    ModbusPropertyModel(
        name = propertyName,
        qualifiedType = transportType.kotlinQualifiedTypeName(),
        valueKind = transportType.valueKind(),
        field =
            ModbusFieldModel(
                codecName = transportType.codecName(),
                registerOffset = registerOffset,
                bitOffset = bitOffset,
                length = length,
                registerWidth = transportType.registerWidth(length),
            ),
        doc = description.cleanDocSummary() ?: name,
    )

private fun CodegenFieldDto.toParameterModel(order: Int): ModbusParameterModel =
    ModbusParameterModel(
        name = propertyName,
        qualifiedType = transportType.kotlinQualifiedTypeName(),
        valueKind = transportType.valueKind(),
        order = order,
        codecName = transportType.codecName(),
        registerOffset = registerOffset,
        bitOffset = bitOffset,
        registerWidth = transportType.registerWidth(length),
        length = length,
        doc = description.cleanDocSummary() ?: name,
    )

private fun CodegenContextDetailDto.modbusTransport(): ModbusTransportKind =
    when (protocolTemplateCode) {
        "MODBUS_TCP_CLIENT" -> ModbusTransportKind.TCP
        else -> ModbusTransportKind.RTU
    }

private fun buildRequestClassName(
    interfaceSimpleName: String,
    transport: ModbusTransportKind,
    methodName: String,
): String {
    val prefix = interfaceSimpleName + transport.transportId.replaceFirstChar(Char::uppercase)
    return prefix + methodName.replaceFirstChar(Char::uppercase) + "Request"
}

private fun buildRequestQualifiedName(
    interfaceSimpleName: String,
    transport: ModbusTransportKind,
    methodName: String,
): String =
    "$MCU_DEVICE_PACKAGE.generated.${buildRequestClassName(interfaceSimpleName, transport, methodName)}"

private fun CodegenTransportType.codecName(): String =
    when (this) {
        CodegenTransportType.BOOL_COIL -> "BOOL_COIL"
        CodegenTransportType.U8 -> "U8"
        CodegenTransportType.U16 -> "U16"
        CodegenTransportType.U32_BE -> "U32_BE"
        CodegenTransportType.BYTE_ARRAY -> "BYTE_ARRAY"
        CodegenTransportType.STRING_ASCII -> "STRING_ASCII"
        CodegenTransportType.STRING_UTF8 -> "STRING_UTF8"
    }

private fun CodegenTransportType.valueKind(): ModbusValueKind =
    when (this) {
        CodegenTransportType.BOOL_COIL -> ModbusValueKind.BOOLEAN
        CodegenTransportType.U8,
        CodegenTransportType.U16,
        CodegenTransportType.U32_BE -> ModbusValueKind.INT
        CodegenTransportType.BYTE_ARRAY -> ModbusValueKind.BYTES
        CodegenTransportType.STRING_ASCII,
        CodegenTransportType.STRING_UTF8 -> ModbusValueKind.STRING
    }

private fun CodegenTransportType.kotlinQualifiedTypeName(): String =
    when (this) {
        CodegenTransportType.BOOL_COIL -> "kotlin.Boolean"
        CodegenTransportType.U8,
        CodegenTransportType.U16,
        CodegenTransportType.U32_BE -> "kotlin.Int"
        CodegenTransportType.BYTE_ARRAY -> "kotlin.ByteArray"
        CodegenTransportType.STRING_ASCII,
        CodegenTransportType.STRING_UTF8 -> "kotlin.String"
    }

private fun CodegenTransportType.registerWidth(
    length: Int,
): Int =
    when (this) {
        CodegenTransportType.BOOL_COIL,
        CodegenTransportType.U8,
        CodegenTransportType.U16 -> 1
        CodegenTransportType.U32_BE -> 2
        CodegenTransportType.BYTE_ARRAY -> (length + 1) / 2
        CodegenTransportType.STRING_ASCII,
        CodegenTransportType.STRING_UTF8 -> length
    }

internal fun String.normalizeGeneratedKotlin(): String =
    lineSequence()
        .joinToString("\n") { line -> line.trimEnd() }
        .trimEnd() + "\n"

internal fun String?.cleanDocSummary(): String? =
    this?.trim()?.takeIf(String::isNotBlank)

private fun String.appendUpsertClause(
    connection: Connection,
): String =
    when {
        connection.isMySql() ->
            this +
                """
                
                ON DUPLICATE KEY UPDATE
                    context_code = VALUES(context_code),
                    context_name = VALUES(context_name),
                    enabled = VALUES(enabled),
                    consumer_target = VALUES(consumer_target),
                    protocol_template_code = VALUES(protocol_template_code),
                    selected = VALUES(selected),
                    payload = VALUES(payload),
                    updated_at = VALUES(updated_at)
                """.trimIndent()

        else -> error("Unsupported metadata snapshot database: ${connection.metaData.databaseProductName}")
    }

private fun PreparedStatement.setUpdatedAt(
    index: Int,
    connection: Connection,
    instant: Instant,
) {
    check(connection.isMySql()) {
        "Unsupported metadata snapshot database: ${connection.metaData.databaseProductName}"
    }
    setTimestamp(index, java.sql.Timestamp.from(instant))
}

private fun Connection.isMySql(): Boolean =
    metaData.databaseProductName.contains("mysql", ignoreCase = true) ||
        metaData.url.contains(":mysql:", ignoreCase = true)

internal fun loadApiModelDoc(
    apiModelPath: Path,
    modelName: String,
): ApiModelDoc? {
    if (!apiModelPath.exists()) {
        return null
    }
    val lines = Files.readAllLines(apiModelPath)
    var pendingDoc: String? = null
    var collectingDoc = false
    val docLines = mutableListOf<String>()
    var classSummary: String? = null
    val propertyDocs = linkedMapOf<String, String>()

    lines.forEach { rawLine ->
        val line = rawLine.trim()
        if (collectingDoc) {
            docLines += line
            if (line.contains("*/")) {
                pendingDoc = docLines.extractKDocSummary()
                docLines.clear()
                collectingDoc = false
            }
            return@forEach
        }
        if (line.startsWith("/**")) {
            docLines.clear()
            docLines += line
            if (line.contains("*/")) {
                pendingDoc = docLines.extractKDocSummary()
                docLines.clear()
            } else {
                collectingDoc = true
            }
            return@forEach
        }
        if (pendingDoc != null && line.startsWith("data class $modelName(")) {
            classSummary = pendingDoc
            pendingDoc = null
            return@forEach
        }
        val propertyName =
            Regex("""(?:val|var)\s+([A-Za-z_][A-Za-z0-9_]*)\s*:""").find(line)?.groupValues?.getOrNull(1)
        if (pendingDoc != null && propertyName != null) {
            propertyDocs[propertyName] = pendingDoc.orEmpty()
            pendingDoc = null
            return@forEach
        }
        if (line.isNotBlank() && !line.startsWith("@")) {
            pendingDoc = null
        }
    }

    if (classSummary == null && propertyDocs.isEmpty()) {
        return null
    }
    return ApiModelDoc(
        classSummary = classSummary,
        propertyDocs = propertyDocs,
    )
}

internal fun List<String>.extractKDocSummary(): String? =
    map { line ->
        line
            .removePrefix("/**")
            .removeSuffix("*/")
            .removePrefix("*")
            .trim()
    }.firstOrNull(String::isNotBlank)
