import fs from "node:fs";
import path from "node:path";

function ensureDirectory(dirPath) {
  fs.mkdirSync(dirPath, {recursive: true});
}

function writeFile(targetFile, content, force) {
  if (!force && fs.existsSync(targetFile)) {
    throw new Error(`Refusing to overwrite existing file: ${targetFile}`);
  }

  ensureDirectory(path.dirname(targetFile));
  fs.writeFileSync(targetFile, content, "utf8");
}

function resolveXiaoeyuDependency(targetDir) {
  const localPackageDir = path.resolve(process.cwd(), "xiaoeyu");
  const localPackageJson = path.join(localPackageDir, "package.json");

  if (!fs.existsSync(localPackageJson)) {
    return "^0.1.0";
  }

  try {
    const packageJson = JSON.parse(fs.readFileSync(localPackageJson, "utf8"));
    if (packageJson.name !== "@addzero/xiaoeyu") {
      return "^0.1.0";
    }

    const relativePackagePath = path.relative(targetDir, localPackageDir).replaceAll("\\", "/");
    return `file:${relativePackagePath || "."}`;
  } catch {
    return "^0.1.0";
  }
}

function buildPackageJson(targetDir) {
  return `${JSON.stringify(
    {
      name: "xiaoeyu-docs",
      version: "0.0.0",
      private: true,
      scripts: {
        docusaurus: "docusaurus",
        "prepare:content": "xiaoeyu generate --config ../xiaoeyu.config.json",
        start: "npm run prepare:content && docusaurus start",
        build: "npm run prepare:content && docusaurus build",
        clear: "docusaurus clear",
        serve: "docusaurus serve"
      },
      dependencies: {
        "@addzero/xiaoeyu": resolveXiaoeyuDependency(targetDir),
        "@easyops-cn/docusaurus-search-local": "0.55.1",
        "@docusaurus/core": "3.9.2",
        "@docusaurus/preset-classic": "3.9.2",
        "@mdx-js/react": "^3.0.0",
        "clsx": "^2.0.0",
        "prism-react-renderer": "^2.3.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0"
      },
      devDependencies: {
        "@docusaurus/module-type-aliases": "3.9.2",
        "@docusaurus/types": "3.9.2"
      },
      engines: {
        node: ">=20.0"
      }
    },
    null,
    2
  )}\n`;
}

function buildDocusaurusConfig() {
  return `import {themes as prismThemes} from "prism-react-renderer";
import {fileURLToPath} from "node:url";
import path from "node:path";
import {createDocusaurusConfig, loadConfig} from "@addzero/xiaoeyu";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const {config: xiaoeyuConfig} = loadConfig("../xiaoeyu.config.json", currentDir);

const config = createDocusaurusConfig(xiaoeyuConfig, {
  customCss: "./custom.css",
  themeConfig: {
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula
    }
  }
});

export default config;
`;
}

function buildSidebar() {
  return `module.exports = {
  docsSidebar: [{type: "autogenerated", dirName: "."}]
};
`;
}

function buildGitignore() {
  return `build
.docusaurus
node_modules
content
.xiaoeyu
`;
}

export function scaffoldSite(options = {}) {
  const targetDir = path.resolve(options.targetDir ?? "docs");
  const force = options.force === true;

  ensureDirectory(targetDir);
  writeFile(path.join(targetDir, "package.json"), buildPackageJson(targetDir), force);
  writeFile(
    path.join(targetDir, "docusaurus.config.mjs"),
    buildDocusaurusConfig(),
    force
  );
  writeFile(path.join(targetDir, "sidebars.js"), buildSidebar(), force);
  writeFile(
    path.join(targetDir, "custom.css"),
    fs.readFileSync(new URL("../template/custom.css", import.meta.url), "utf8"),
    force
  );
  writeFile(path.join(targetDir, ".gitignore"), buildGitignore(), force);

  return {
    targetDir
  };
}
