ALTER TABLE codegen_context_context
    ADD COLUMN server_output_root VARCHAR(1024) NULL AFTER external_c_output_root,
    ADD COLUMN shared_output_root VARCHAR(1024) NULL AFTER server_output_root,
    ADD COLUMN gateway_output_root VARCHAR(1024) NULL AFTER shared_output_root,
    ADD COLUMN api_client_output_root VARCHAR(1024) NULL AFTER gateway_output_root,
    ADD COLUMN api_client_package_name VARCHAR(255) NULL AFTER api_client_output_root,
    ADD COLUMN spring_route_output_root VARCHAR(1024) NULL AFTER api_client_package_name,
    ADD COLUMN c_output_root VARCHAR(1024) NULL AFTER spring_route_output_root,
    ADD COLUMN markdown_output_root VARCHAR(1024) NULL AFTER c_output_root,
    ADD COLUMN rtu_port_path VARCHAR(255) NOT NULL DEFAULT '/dev/ttyUSB0' AFTER markdown_output_root,
    ADD COLUMN rtu_unit_id INT NOT NULL DEFAULT 1 AFTER rtu_port_path,
    ADD COLUMN rtu_baud_rate INT NOT NULL DEFAULT 9600 AFTER rtu_unit_id,
    ADD COLUMN rtu_data_bits INT NOT NULL DEFAULT 8 AFTER rtu_baud_rate,
    ADD COLUMN rtu_stop_bits INT NOT NULL DEFAULT 1 AFTER rtu_data_bits,
    ADD COLUMN rtu_parity VARCHAR(64) NOT NULL DEFAULT 'none' AFTER rtu_stop_bits,
    ADD COLUMN rtu_timeout_ms BIGINT NOT NULL DEFAULT 1000 AFTER rtu_parity,
    ADD COLUMN rtu_retries INT NOT NULL DEFAULT 2 AFTER rtu_timeout_ms,
    ADD COLUMN tcp_host VARCHAR(255) NOT NULL DEFAULT '127.0.0.1' AFTER rtu_retries,
    ADD COLUMN tcp_port INT NOT NULL DEFAULT 502 AFTER tcp_host,
    ADD COLUMN tcp_unit_id INT NOT NULL DEFAULT 1 AFTER tcp_port,
    ADD COLUMN tcp_timeout_ms BIGINT NOT NULL DEFAULT 1000 AFTER tcp_unit_id,
    ADD COLUMN tcp_retries INT NOT NULL DEFAULT 2 AFTER tcp_timeout_ms;
