ktor {
    deployment {
        port = 18080
        port = ${?SERVER_PORT}
        host = "0.0.0.0"
        host = ${?SERVER_HOST}
    }
    application {
        modules = [site.addzero.notes.server.ApplicationKt.module]
    }
}
