package site.addzero.starter.flyway

data class FlywayDefaults(
    val locations: List<String>? = null,
    val baselineOnMigrate: Boolean? = null,
    val baselineVersion: String? = null,
    val cleanDisabled: Boolean? = null,
    val connectRetries: Int? = null,
    val group: Boolean? = null,
    val installedBy: String? = null,
    val mixed: Boolean? = null,
    val outOfOrder: Boolean? = null,
    val placeholderReplacement: Boolean? = null,
    val placeholderPrefix: String? = null,
    val placeholderSuffix: String? = null,
    val placeholders: Map<String, String>? = null,
    val schemas: List<String>? = null,
    val skipDefaultCallbacks: Boolean? = null,
    val skipDefaultResolvers: Boolean? = null,
    val sqlMigrationPrefix: String? = null,
    val sqlMigrationSeparator: String? = null,
    val sqlMigrationSuffixes: List<String>? = null,
    val table: String? = null,
    val target: String? = null,
    val validateOnMigrate: Boolean? = null,
    val ignoreMigrationPatterns: List<String>? = null,
) {
    fun mergeWith(other: FlywayDefaults): FlywayDefaults {
        return FlywayDefaults(
            locations = locations ?: other.locations,
            baselineOnMigrate = baselineOnMigrate ?: other.baselineOnMigrate,
            baselineVersion = baselineVersion ?: other.baselineVersion,
            cleanDisabled = cleanDisabled ?: other.cleanDisabled,
            connectRetries = connectRetries ?: other.connectRetries,
            group = group ?: other.group,
            installedBy = installedBy ?: other.installedBy,
            mixed = mixed ?: other.mixed,
            outOfOrder = outOfOrder ?: other.outOfOrder,
            placeholderReplacement = placeholderReplacement ?: other.placeholderReplacement,
            placeholderPrefix = placeholderPrefix ?: other.placeholderPrefix,
            placeholderSuffix = placeholderSuffix ?: other.placeholderSuffix,
            placeholders = placeholders ?: other.placeholders,
            schemas = schemas ?: other.schemas,
            skipDefaultCallbacks = skipDefaultCallbacks ?: other.skipDefaultCallbacks,
            skipDefaultResolvers = skipDefaultResolvers ?: other.skipDefaultResolvers,
            sqlMigrationPrefix = sqlMigrationPrefix ?: other.sqlMigrationPrefix,
            sqlMigrationSeparator = sqlMigrationSeparator ?: other.sqlMigrationSeparator,
            sqlMigrationSuffixes = sqlMigrationSuffixes ?: other.sqlMigrationSuffixes,
            table = table ?: other.table,
            target = target ?: other.target,
            validateOnMigrate = validateOnMigrate ?: other.validateOnMigrate,
            ignoreMigrationPatterns = ignoreMigrationPatterns ?: other.ignoreMigrationPatterns,
        )
    }
}
