// Generated by codegen-context. DO NOT EDIT.
package site.addzero.kcloud.plugins.mcuconsole.modbus.device

/**
 * 读取板卡快照寄存器。
 */
data class BoardSnapshotRegisters(
    /**
     * 运行时长，单位毫秒。
     */
    val uptimeMs: Int,
    /**
     * 设备标签。
     */
    val deviceLabel: String
)
