// Generated by codegen-context. DO NOT EDIT.
package site.addzero.kcloud.plugins.mcuconsole.modbus.device

import site.addzero.device.protocol.modbus.annotation.ModbusField
import site.addzero.device.protocol.modbus.model.ModbusCodec

data class BoardSnapshotRegisters(
    @ModbusField(codec = ModbusCodec.U32_BE, registerOffset = 0)
    val uptimeMs: Int,
    @ModbusField(codec = ModbusCodec.STRING_ASCII, registerOffset = 2, length = 4)
    val deviceLabel: String,
) {
}
