// Generated by codegen-context. DO NOT EDIT.
package site.addzero.kcloud.plugins.mcuconsole.modbus.device

interface DeviceApi {
    /**
     * 读取板卡快照寄存器。
     */
    suspend fun readBoardSnapshot(): BoardSnapshotRegisters
}
