// Generated by codegen-context. DO NOT EDIT.
package site.addzero.kcloud.plugins.mcuconsole.modbus.device

import site.addzero.device.protocol.modbus.annotation.ModbusOperation
import site.addzero.device.protocol.modbus.annotation.ModbusParam
import site.addzero.device.protocol.modbus.model.ModbusCodec
import site.addzero.device.protocol.modbus.model.ModbusCommandResult
import site.addzero.device.protocol.modbus.model.ModbusFunctionCode

interface DeviceWriteApi {
    @ModbusOperation(
        address = 30,
        functionCode = ModbusFunctionCode.WRITE_MULTIPLE_REGISTERS,
    )
    suspend fun writeBoardConfig(
        @ModbusParam(order = 0, codec = ModbusCodec.U16)
        threshold: Int,
        @ModbusParam(order = 1, codec = ModbusCodec.STRING_UTF8, registerOffset = 1, length = 2)
        note: String,
    ): ModbusCommandResult
}
