// Generated by codegen-context. DO NOT EDIT.
package site.addzero.kcloud.plugins.mcuconsole.modbus.device

import site.addzero.device.protocol.modbus.model.ModbusCommandResult

interface DeviceWriteApi {
    /**
     * 写入板卡配置寄存器。
     */
    suspend fun writeBoardConfig(
        threshold: Int,
        note: String
    ): ModbusCommandResult
}
