// Generated by codegen-context. DO NOT EDIT.
package site.addzero.kcloud.plugins.mcuconsole.modbus.device

import site.addzero.device.protocol.modbus.annotation.ModbusOperation
import site.addzero.device.protocol.modbus.model.ModbusFunctionCode

interface DeviceApi {
    @ModbusOperation(
        address = 10,
        functionCode = ModbusFunctionCode.READ_HOLDING_REGISTERS,
    )
    suspend fun readBoardSnapshot(): BoardSnapshotRegisters
}
